import React,{useMemo,useState} from 'react';
import './finance-accounts.css';
import HowWorks from "../how-works.jsx";

const BRAND={name:'TechTarn',website:'www.techtarn.com',phone:'+90 - 7453966757',email:'contact@techtarn.com'};
const modules=['Dashboard','AR','AP','GL','Payments','Tax','Costing','Reports','Settings'];
const tours={Dashboard:'Review receivables, payables, cash and tax KPIs.',AR:'Create and manage customer invoices and receivables.',AP:'Create supplier bills and track payable status.',GL:'Post and review journal entries with debit/credit controls.',Payments:'Record incoming and outgoing payments and reconciliation status.',Tax:'Maintain tax codes, rates and filing status.',Costing:'Maintain product/production cost components and totals.',Reports:'Review finance reports and export a report snapshot.',Settings:'Save finance preferences and fiscal settings.'};
const seed={
 ar:[['AR-1001','CUST-001','FreshMart Retail','INV-26091','2026-09-05','2026-10-05',125000,'INR','Open'],['AR-1002','CUST-002','City Foods','INV-26092','2026-09-12','2026-09-27',84000,'INR','Part Paid'],['AR-1003','CUST-003','Green Basket','INV-26093','2026-08-20','2026-09-19',56000,'INR','Overdue']],
 ap:[['AP-2001','SUP-101','Prime Ingredients','BILL-8821','2026-09-04','2026-10-04',98000,'INR','Open'],['AP-2002','SUP-102','PackRight Ltd','BILL-8822','2026-09-15','2026-09-30',45000,'INR','Approved'],['AP-2003','SUP-103','ColdChain Services','BILL-8823','2026-08-18','2026-09-18',32000,'INR','Overdue']],
 gl:[['JE-3001','2026-09-24','RM Purchase','2100 Inventory','120000','120000','Approved'],['JE-3002','2026-09-24','Customer Receipt','1100 Bank','84000','84000','Posted'],['JE-3003','2026-09-25','Utilities Accrual','5200 Utilities','18000','18000','Draft']],
 payments:[['PAY-4001','2026-09-24','Customer Receipt','FreshMart Retail','AR-1001',75000,'INR','Bank','Reconciled'],['PAY-4002','2026-09-25','Supplier Payment','Prime Ingredients','AP-2001',50000,'INR','Bank','Pending'],['PAY-4003','2026-09-25','Supplier Payment','ColdChain Services','AP-2003',32000,'INR','Bank','Reconciled']],
 tax:[['TAX-5001','GST-18','GST Standard','Goods','18','Output/Input','Active'],['TAX-5002','GST-5','GST Reduced','Food items','5','Output/Input','Active'],['TAX-5003','TDS-2','TDS Services','Services','2','Withholding','Active']],
 costing:[['CST-6001','Milk Pasteurized 1L','Raw Material',42.5,'INR/L','Standard','Active'],['CST-6002','Fruit Yogurt 500g','Raw Material',31.75,'INR/Pack','Standard','Active'],['CST-6003','Fruit Yogurt 500g','Conversion',8.25,'INR/Pack','Standard','Active']]
};
const configs={
 AR:{key:'ar',title:'Accounts Receivable',fields:['Ref','Customer ID','Customer','Invoice','Invoice Date','Due Date','Amount','Currency','Status'],inputs:['Customer ID','Customer','Invoice','Invoice Date','Due Date','Amount','Currency','Status']},
 AP:{key:'ap',title:'Accounts Payable',fields:['Ref','Supplier ID','Supplier','Bill','Bill Date','Due Date','Amount','Currency','Status'],inputs:['Supplier ID','Supplier','Bill','Bill Date','Due Date','Amount','Currency','Status']},
 GL:{key:'gl',title:'General Ledger',fields:['Entry','Date','Narration','Account','Debit','Credit','Status'],inputs:['Date','Narration','Account','Debit','Credit','Status']},
 Payments:{key:'payments',title:'Payments & Receipts',fields:['Payment','Date','Type','Party','Reference','Amount','Currency','Method','Status'],inputs:['Date','Type','Party','Reference','Amount','Currency','Method','Status']},
 Tax:{key:'tax',title:'Tax Master',fields:['Code','Tax Code','Name','Scope','Rate %','Treatment','Status'],inputs:['Tax Code','Name','Scope','Rate %','Treatment','Status']},
 Costing:{key:'costing',title:'Costing',fields:['Cost ID','Product','Component','Unit Cost','Unit','Method','Status'],inputs:['Product','Component','Unit Cost','Unit','Method','Status']}
};
function Login({onLogin}){const [email,setEmail]=useState('finance@techtarn.com'),[pw,setPw]=useState('Demo@123'),[panel,setPanel]=useState('Finance & Accounts'),[err,setErr]=useState(''); const submit=e=>{e.preventDefault(); if((email==='finance@techtarn.com'||email==='admin@techtarn.com')&&pw==='Demo@123')onLogin(); else setErr('Invalid demo credentials. Use finance@techtarn.com / Demo@123');}; return <div className="login"><div className="login-card"><div className="brand"><span className="logo">T</span><div><b>{BRAND.name}</b><small>Food Processing ERP</small></div></div><h1>Finance & Accounts</h1><p>Secure demo login</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={pw} onChange={e=>setPw(e.target.value)} required/></label><label>Panel<select value={panel} onChange={e=>setPanel(e.target.value)}><option>Finance & Accounts</option></select></label>{err&&<div className="error">{err}</div>}<button className="primary">Sign in</button></form><div className="demo">Demo: finance@techtarn.com · Demo@123</div></div></div>}
export default function App(){const [logged,setLogged]=useState(true); if(!logged)return <Login onLogin={()=>setLogged(true)}/>; return <ERP/>}
function ERP(){const [active,setActive]=useState('Dashboard'),[data,setData]=useState(seed),[toast,setToast]=useState(''),[query,setQuery]=useState(''),[tour,setTour]=useState(true),[tourIdx,setTourIdx]=useState(0),[mobile,setMobile]=useState(false),[edit,setEdit]=useState(null); const show=m=>{setActive(m);setQuery('');setMobile(false)}; const notify=m=>{setToast(m);setTimeout(()=>setToast(''),1800)};
 const totals=useMemo(()=>({ar:data.ar.reduce((s,r)=>s+Number(r[6]||0),0),ap:data.ap.reduce((s,r)=>s+Number(r[6]||0),0),payments:data.payments.reduce((s,r)=>s+Number(r[5]||0),0)}),[data]);
 const addRow=(cfg,values)=>{const refPrefix=cfg.key==='ar'?'AR':cfg.key==='ap'?'AP':cfg.key==='gl'?'JE':cfg.key==='payments'?'PAY':cfg.key==='tax'?'TAX':'CST'; const n=String(data[cfg.key].length+1).padStart(4,'0'); let row=[`${refPrefix}-${n}`,...values]; if(cfg.key==='gl'&&Number(values[3]||0)!==Number(values[4]||0)){notify('GL entry rejected: Debit must equal Credit');return} setData(d=>({...d,[cfg.key]:[...d[cfg.key],row]}));notify(`${cfg.title} entry added`)};
 const del=(key,i)=>{setData(d=>({...d,[key]:d[key].filter((_,x)=>x!==i)}));notify('Entry deleted')};
 const update=(key,i,row)=>{setData(d=>({...d,[key]:d[key].map((r,x)=>x===i?row:r)}));setEdit(null);notify('Entry updated')};
 return <div className="app"><aside className={mobile?'open':''}><div className="brand side"><span className="logo">T</span><div><b>{BRAND.name}</b><small>Finance ERP</small></div></div><nav>{modules.map(m=><button key={m} className={active===m?'active':''} onClick={()=>show(m)}>{m}</button>)}</nav><div className="side-foot">finance@techtarn.com<br/><button onClick={()=>location.reload()}>Logout</button></div></aside><main><header><button className="hamb" onClick={()=>setMobile(!mobile)}>☰</button><div><b>Finance & Accounts</b><span> / {active}</span></div><div className="head-actions"><span className="user">Finance Manager</span><button onClick={()=>setTour(true)}>Guide Tour</button></div></header><section className="hero"><div><h1>{active}</h1><p>{tours[active]}</p></div><div className="hero-actions">{active!=='Dashboard'&&configs[active]&&<button className="primary" onClick={()=>setEdit({mode:'add',key:configs[active].key})}>+ Add Entry</button>}</div></section>{active==='Dashboard'?<Dashboard totals={totals} data={data} show={show}/>:active==='Reports'?<Reports data={data} notify={notify}/>:active==='Settings'?<Settings notify={notify}/>:configs[active]?<FinanceTable cfg={configs[active]} rows={data[configs[active].key]} query={query} setQuery={setQuery} onAdd={v=>addRow(configs[active],v)} onDelete={i=>del(configs[active].key,i)} onEdit={(i,row)=>setEdit({mode:'edit',key:configs[active].key,index:i,row})}/>:null}{edit&&<EntryModal cfg={configs[Object.keys(configs).find(k=>configs[k].key===edit.key)]} edit={edit} close={()=>setEdit(null)} save={(v)=>edit.mode==='add'?addRow(configs[Object.keys(configs).find(k=>configs[k].key===edit.key)],v):update(edit.key,edit.index,[edit.row[0],...v])}/>} {tour&&<Tour active={active} idx={tourIdx} setIdx={setTourIdx} close={()=>setTour(false)} show={show}/>} {toast&&<div className="toast">{toast}</div>}<HowWorks panel="Finance & Accounts" module={active}/></main></div>}
function Dashboard({totals,data,show}){const cards=[['AR Outstanding',totals.ar.toLocaleString('en-IN')],['AP Outstanding',totals.ap.toLocaleString('en-IN')],['Payments',totals.payments.toLocaleString('en-IN')],['Tax Codes',data.tax.length],['Cost Lines',data.costing.length],['GL Entries',data.gl.length]];return <section className="content"><div className="stats">{cards.map(c=><div className="stat" key={c[0]}><span>{c[0]}</span><strong>{c[1]}</strong><small>INR / records</small></div>)}</div><div className="grid2"><div className="panel"><h3>Finance workflow</h3>{[['AR','Invoice → Due → Receipt'],['AP','Bill → Approval → Payment'],['GL','Draft → Balance → Post'],['Payments','Receipt/Payment → Reconcile'],['Tax','Code → Rate → Filing'],['Costing','Component → Unit Cost → Standard']].map(x=><button className="workflow" key={x[0]} onClick={()=>show(x[0])}><b>{x[0]}</b><span>{x[1]}</span>›</button>)}</div><div className="panel"><h3>Attention</h3><div className="alert">{data.ar.filter(r=>r[8]==='Overdue').length} overdue receivables</div><div className="alert">{data.ap.filter(r=>r[8]==='Overdue').length} overdue payables</div><div className="alert">GL validation requires balanced debit/credit</div></div></div></section>}
function FinanceTable({cfg,rows,query,setQuery,onAdd,onDelete,onEdit}){const filtered=rows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase()));return <section className="content"><div className="toolbar"><input placeholder={`Search ${cfg.title}...`} value={query} onChange={e=>setQuery(e.target.value)}/><span>{filtered.length} records</span></div><div className="table-wrap"><table><thead><tr>{cfg.fields.map(f=><th key={f}>{f}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map((r,idx)=><tr key={r[0]}>{r.map((c,i)=><td key={i}><span className={i===r.length-1?'badge':''}>{c}</span></td>)}<td><button onClick={()=>onEdit(rows.indexOf(r),r)}>Edit</button><button className="danger" onClick={()=>onDelete(rows.indexOf(r))}>Delete</button></td></tr>)}</tbody></table></div>{filtered.length===0&&<div className="empty">No matching records.</div>}</section>}
function EntryModal({cfg,edit,close,save}){const initial=edit.mode==='edit'?edit.row.slice(1):Array(cfg.inputs.length).fill('');const [v,setV]=useState(initial);const set=(i,x)=>setV(a=>a.map((z,n)=>n===i?x:z)); const submit=e=>{e.preventDefault(); if(v.some(x=>String(x).trim()===''))return; save(v)};return <div className="overlay"><div className="modal"><div className="modal-head"><div><h2>{edit.mode==='add'?'Add':'Edit'} {cfg.title}</h2><p>Enter all required finance data.</p></div><button onClick={close}>×</button></div><form onSubmit={submit}><div className="form-grid">{cfg.inputs.map((f,i)=><label key={f}>{f}<input type={/date/i.test(f)?'date':/amount|debit|credit|rate|cost/i.test(f)?'number':'text'} step="any" value={v[i]??''} onChange={e=>set(i,e.target.value)} required/></label>)}</div><div className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary">Save Entry</button></div></form></div></div>}
function Reports({data,notify}){const report=[['AR Aging',data.ar.length],['AP Aging',data.ap.length],['GL Journal',data.gl.length],['Payments Register',data.payments.length],['Tax Summary',data.tax.length],['Costing Sheet',data.costing.length]];return <section className="content"><div className="report-grid">{report.map(r=><div className="report" key={r[0]}><h3>{r[0]}</h3><strong>{r[1]}</strong><p>Finance records available</p><button onClick={()=>notify(`${r[0]} export prepared`)}>Export CSV</button></div>)}</div></section>}
function Settings({notify}){const [company,setCompany]=useState('TechTarn Food Processing'),[fy,setFy]=useState('2026-27'),[currency,setCurrency]=useState('INR');return <section className="content"><div className="panel settings"><h3>Finance Settings</h3><div className="form-grid"><label>Company<input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Fiscal Year<input value={fy} onChange={e=>setFy(e.target.value)}/></label><label>Base Currency<input value={currency} onChange={e=>setCurrency(e.target.value)}/></label><label>Tax Period<select defaultValue="Monthly"><option>Monthly</option><option>Quarterly</option></select></label></div><button className="primary" onClick={()=>notify('Finance settings saved')}>Save Settings</button></div></section>}
function Tour({active,idx,setIdx,close,show}){const list=modules; const step=list[idx]||active; const next=()=>{if(idx<list.length-1){const n=idx+1;setIdx(n);show(list[n])}else close()};return <div className="tour"><div className="tour-top"><b>Guide Tour</b><button onClick={close}>×</button></div><strong>{idx+1}. {step}</strong><p>{tours[step]}</p><div className="tour-actions"><button disabled={idx===0} onClick={()=>{const n=idx-1;setIdx(n);show(list[n])}}>Back</button><button className="primary" onClick={next}>{idx===list.length-1?'Finish':'Next'}</button></div></div>}
