import React,{useState}from"react";
import HowWorks from "../how-works.jsx";
import{LayoutDashboard,ShieldCheck,Target,GitBranch,ClipboardCheck,BarChart3,Settings,Menu,LogOut,Plus,Search,Trash2,CheckCircle2,Save,X,ChevronRight,Download,AlertTriangle,FileText}from"lucide-react";
import"./food-safety.css";

const BRAND={name:"TechTarn",website:"www.techtarn.com",phone:"+90 - 7453966757",email:"contact@techtarn.com"};
const PANELS=["Super Admin","Management / CEO","Sales & CRM","Purchase","Production","Quality / QA-QC","Raw Material / Inventory","Warehouse","Food Safety","Maintenance","Machine Operator","Finance & Accounts","HR & Payroll","Logistics / Distribution","Reports & Analytics"];
const DATA={
haccp:[
{id:"HAC-1001",plan:"Tomato Puree HACCP Plan",product:"Tomato Puree 1kg",version:"3.2",owner:"Food Safety Lead",review:"2026-12-15",status:"Active"},
{id:"HAC-1002",plan:"Mango Pulp HACCP Plan",product:"Mango Pulp 850g",version:"2.4",owner:"QA Manager",review:"2026-11-30",status:"Active"},
{id:"HAC-1003",plan:"Mixed Fruit Jam HACCP Plan",product:"Mixed Fruit Jam 500g",version:"1.8",owner:"QA Supervisor",review:"2026-10-20",status:"Review Due"}],
ccp:[
{id:"CCP-2001",process:"Thermal Processing",step:"Pasteurization",hazard:"Biological",limit:"≥ 90°C / 5 min",actual:"92°C / 6 min",monitor:"Line Operator",date:"2026-09-28",status:"Compliant"},
{id:"CCP-2002",process:"Metal Detection",step:"Final Inspection",hazard:"Physical",limit:"Fe ≤ 2.0 mm",actual:"Pass",monitor:"QC Analyst",date:"2026-09-29",status:"Compliant"},
{id:"CCP-2003",process:"Cold Storage",step:"Temperature Control",hazard:"Biological",limit:"≤ 5°C",actual:"7.2°C",monitor:"Warehouse Lead",date:"2026-09-30",status:"Deviation"}],
trace:[
{id:"TRC-3001",finished:"FG-TP-260928",product:"Tomato Puree 1kg",batch:"BTH-3001",rawLot:"TP-260901",supplier:"Agro Foods Ltd.",production:"2026-09-28",status:"Traceable"},
{id:"TRC-3002",finished:"FG-MP-260929",product:"Mango Pulp 850g",batch:"BTH-3002",rawLot:"MP-260902",supplier:"Fresh Harvest Co.",production:"2026-09-29",status:"Traceable"},
{id:"TRC-3003",finished:"FG-JM-260930",product:"Mixed Fruit Jam 500g",batch:"BTH-3003",rawLot:"SG-260903",supplier:"Agro Ingredients",production:"2026-09-30",status:"Review"}],
records:[
{id:"FSR-4001",type:"Sanitation Checklist",area:"Production Line A",date:"2026-09-28",owner:"Sanitation Lead",reference:"SAN-2801",status:"Completed"},
{id:"FSR-4002",type:"Allergen Verification",area:"Packing Area",date:"2026-09-29",owner:"QA Analyst",reference:"ALG-2901",status:"Completed"},
{id:"FSR-4003",type:"Temperature Log",area:"Cold Store",date:"2026-09-30",owner:"Warehouse Lead",reference:"TMP-3001",status:"Open"}]
};
const EMPTY={
haccp:{plan:"",product:"",version:"1.0",owner:"",review:"",status:"Draft"},
ccp:{process:"",step:"",hazard:"Biological",limit:"",actual:"",monitor:"",date:"",status:"Compliant"},
trace:{finished:"",product:"",batch:"",rawLot:"",supplier:"",production:"",status:"Traceable"},
records:{type:"",area:"",date:"",owner:"",reference:"",status:"Open"}
};
const TOUR=[["Dashboard","Review HACCP status, CCP deviations and traceability records."],["HACCP","Maintain controlled HACCP plans, versions, owners and review dates."],["CCP","Record critical control point limits, actual readings and deviations."],["Traceability","Connect finished products to batches, raw lots and suppliers."],["Food Safety Records","Maintain sanitation, allergen, temperature and other evidence."],["Reports","Export food safety summaries and compliance information."],["Settings","Save food safety operating preferences."]];

export default function App(){
const[logged,setLogged]=useState(true),[email,setEmail]=useState("foodsafety@techtarn.com"),[password,setPassword]=useState("Demo@123"),[panel,setPanel]=useState("Food Safety"),[tab,setTab]=useState("Dashboard"),[mobile,setMobile]=useState(false),[query,setQuery]=useState(""),[data,setData]=useState(DATA),[modal,setModal]=useState(null),[form,setForm]=useState(null),[toast,setToast]=useState(""),[tour,setTour]=useState(0);
const nav=[["Dashboard",LayoutDashboard],["HACCP",ShieldCheck],["CCP",Target],["Traceability",GitBranch],["Food Safety Records",ClipboardCheck],["Reports",BarChart3],["Settings",Settings]];
const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)},go=n=>{setTab(n);setMobile(false)},show=k=>{setModal(k);setForm({...EMPTY[k]})},close=()=>{setModal(null);setForm(null)};
const filtered=k=>data[k].filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
const add=k=>{const p={haccp:"HAC",ccp:"CCP",trace:"TRC",records:"FSR"}[k];const id=`${p}-${String(data[k].length+1).padStart(4,"0")}`;setData({...data,[k]:[{id,...form},...data[k]]});close();notify("Record saved successfully.")};
const del=(k,id)=>{setData({...data,[k]:data[k].filter(r=>r.id!==id)});notify("Record deleted.")};
const status=(k,id,s)=>{setData({...data,[k]:data[k].map(r=>r.id===id?{...r,status:s}:r)});notify(`Status updated to ${s}.`)};
const login=e=>{e.preventDefault();if((email==="foodsafety@techtarn.com"||email==="admin@techtarn.com")&&password==="Demo@123")setLogged(true);else notify("Use the demo credentials.")};
if(!logged)return <div className="login"><div className="loginCard"><div className="brand"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="loginTitle"><h1>Food Safety</h1><p>HACCP • CCP • Traceability • Food Safety Records</p></div><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Panel<select value={panel} onChange={e=>setPanel(e.target.value)}>{PANELS.map(x=><option key={x}>{x}</option>)}</select></label><button className="primary wide">Login <ChevronRight size={17}/></button></form><div className="demo">Demo: foodsafety@techtarn.com / Demo@123</div></div></div>;

const counts={haccp:data.haccp.length,ccp:data.ccp.filter(x=>x.status!=="Compliant").length,trace:data.trace.length,records:data.records.filter(x=>x.status!=="Completed").length};
const Table=({k,cols})=><div className="tableWrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}<th>Actions</th></tr></thead><tbody>{filtered(k).map(r=><tr key={r.id}>{cols.map(c=><td key={c[0]}>{c[0]==="status"?<span className={`badge ${String(r[c[0]]).toLowerCase().replaceAll(" ","-")}`}>{r[c[0]]}</span>:r[c[0]]}</td>)}<td className="actions">{k==="haccp"&&r.status==="Review Due"&&<button className="iconBtn" title="Mark active" onClick={()=>status(k,r.id,"Active")}><CheckCircle2 size={15}/></button>}{k==="ccp"&&r.status==="Deviation"&&<button className="iconBtn" title="Resolve deviation" onClick={()=>status(k,r.id,"Compliant")}><CheckCircle2 size={15}/></button>}{k==="trace"&&r.status==="Review"&&<button className="iconBtn" title="Mark traceable" onClick={()=>status(k,r.id,"Traceable")}><CheckCircle2 size={15}/></button>}{k==="records"&&r.status==="Open"&&<button className="iconBtn" title="Complete record" onClick={()=>status(k,r.id,"Completed")}><CheckCircle2 size={15}/></button>}<button className="iconBtn danger" title="Delete" onClick={()=>del(k,r.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>;
const moduleView=(title,sub,k,cols,label)=><><div className="hero compact"><div><p className="eyebrow">FOOD SAFETY</p><h1>{title}</h1><p>{sub}</p></div><button className="primary" onClick={()=>show(k)}><Plus size={17}/>{label}</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered(k).length} record(s)</span></div><div className="card"><Table k={k} cols={cols}/></div></>;

const content=()=>{
if(tab==="Dashboard")return <><div className="hero"><div><p className="eyebrow">FOOD SAFETY CONTROL CENTER</p><h1>Food Safety Dashboard</h1><p>Manage HACCP plans, critical control points, traceability and food safety evidence.</p></div><button className="primary" onClick={()=>show("ccp")}><Plus size={17}/> New CCP Record</button></div><div className="stats">{[["HACCP Plans",counts.haccp,ShieldCheck,"HACCP"],["CCP Attention",counts.ccp,Target,"CCP"],["Traceability",counts.trace,GitBranch,"Traceability"],["Open Records",counts.records,ClipboardCheck,"Food Safety Records"]].map(([l,v,I,t])=><div className="stat" key={l}><div className="statIcon"><I size={18}/></div><div><span>{l}</span><strong>{v}</strong></div><button onClick={()=>go(t)}>Open</button></div>)}</div><div className="grid2"><div className="card"><div className="cardHead"><div><h3>Food safety workflow</h3><p>Maintain preventive controls and objective evidence.</p></div></div>{["HACCP plan control","CCP monitoring","Traceability linkage","Food safety records"].map((x,i)=><div className="workflow" key={x}><b>{i+1}</b><span>{x}</span><ChevronRight size={16}/></div>)}</div><div className="card"><div className="cardHead"><div><h3>Attention required</h3><p>Current food safety exceptions.</p></div></div><div className="alert"><AlertTriangle size={17}/><span><b>{data.ccp.filter(x=>x.status==="Deviation").length}</b> CCP deviation(s)</span></div><div className="alert"><AlertTriangle size={17}/><span><b>{data.haccp.filter(x=>x.status==="Review Due").length}</b> HACCP plan(s) due for review</span></div><div className="alert"><FileText size={17}/><span><b>{counts.records}</b> food safety record(s) open</span></div></div></div></div></>;
if(tab==="HACCP")return moduleView("HACCP","Maintain controlled HACCP plans, versions, owners and review dates.","haccp",[["id","Plan ID"],["plan","Plan"],["product","Product"],["version","Version"],["owner","Owner"],["review","Review Date"],["status","Status"]],"Add HACCP Plan");
if(tab==="CCP")return moduleView("CCP","Record critical limits, actual readings and monitoring status.","ccp",[["id","CCP ID"],["process","Process"],["step","Step"],["hazard","Hazard"],["limit","Critical Limit"],["actual","Actual"],["monitor","Monitor"],["date","Date"],["status","Status"]],"Add CCP Record");
if(tab==="Traceability")return moduleView("Traceability","Link finished goods to production batches, raw lots and suppliers.","trace",[["id","Trace ID"],["finished","Finished Lot"],["product","Product"],["batch","Batch"],["rawLot","Raw Lot"],["supplier","Supplier"],["production","Production"],["status","Status"]],"Add Trace Record");
if(tab==="Food Safety Records")return moduleView("Food Safety Records","Maintain sanitation, allergen, temperature and other safety evidence.","records",[["id","Record ID"],["type","Record Type"],["area","Area"],["date","Date"],["owner","Owner"],["reference","Reference"],["status","Status"]],"Add Food Safety Record");
if(tab==="Reports")return <><div className="hero compact"><div><p className="eyebrow">REPORTING</p><h1>Food Safety Reports</h1><p>Review HACCP, CCP, traceability and food safety record summaries.</p></div><button className="secondary" onClick={()=>notify("Food safety report export prepared.")}><Download size={17}/> Export Report</button></div><div className="reportGrid">{[["HACCP Plans",counts.haccp,"Controlled plans"],["CCP Attention",counts.ccp,"Deviations requiring review"],["Traceability",counts.trace,"Traceable product records"],["Open Records",counts.records,"Records requiring completion"]].map(([a,b,c])=><div className="reportCard" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small><div className="bar"><i style={{width:`${Math.min(100,Math.max(12,b*18))}%`}}/></div></div>)}</div></>;
return <div className="card settings"><div className="cardHead"><div><h2>Food Safety Settings</h2><p>Configure food safety operating preferences for this prototype.</p></div></div><div className="formGrid"><label>Food Safety Site<input defaultValue="TechTarn Food Processing — Main Plant"/></label><label>HACCP Review Cycle<select defaultValue="Annual"><option>Quarterly</option><option>Annual</option></select></label><label>CCP Escalation<select defaultValue="Immediate"><option>Immediate</option><option>1 hour</option><option>4 hours</option></select></label><label>Record Owner<input defaultValue="Food Safety Lead"/></label></div><button className="primary" onClick={()=>notify("Settings saved successfully.")}><Save size={17}/> Save Settings</button></div>;
};

const fields={haccp:["plan","product","version","owner","review","status"],ccp:["process","step","hazard","limit","actual","monitor","date","status"],trace:["finished","product","batch","rawLot","supplier","production","status"],records:["type","area","date","owner","reference","status"]};
const titles={haccp:"Add HACCP Plan",ccp:"Add CCP Record",trace:"Add Traceability Record",records:"Add Food Safety Record"};
const opts={haccp:["Draft","Active","Review Due","Inactive"],ccp:["Compliant","Deviation","Review"],trace:["Traceable","Review","Hold"],records:["Open","Completed","Review"]};
const Modal=({k})=><div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><div><h2>{titles[k]}</h2><p>Enter the food safety data and save the record.</p></div><button className="iconBtn" onClick={close}><X size={18}/></button></div><div className="formGrid">{fields[k].map(f=><label key={f}>{f.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())}{f==="status"?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{opts[k].map(o=><option key={o}>{o}</option>)}</select>:f==="hazard"?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{["Biological","Chemical","Physical","Allergen"].map(o=><option key={o}>{o}</option>)}</select>:<input required value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})} type={["review","date","production"].includes(f)?"date":"text"} placeholder={`Enter ${f}`}/>}</label>)}</div><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>add(k)}><Save size={17}/> Save Record</button></div></div></div>;

return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand side"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="panelTag">Food Safety</div><nav>{nav.map(([n,I])=><button key={n} className={tab===n?"nav active":"nav"} onClick={()=>go(n)}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideFoot"><span>Logged in as</span><b>{email}</b><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></aside><main><header><button className="menuBtn" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div><b>{tab}</b><span>Food Safety Panel</span></div><div className="headRight"><span>{BRAND.website}</span><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></header><section className="main">{content()}</section><HowWorks panel="Food Safety" module={tab}/></main><div className="tour"><div><b>Guide Tour · {tour+1}/{TOUR.length}</b><span>{TOUR[tour][0]} — {TOUR[tour][1]}</span></div><div className="tourBtns"><button disabled={tour===0} onClick={()=>setTour(Math.max(0,tour-1))}>Back</button><button className="primary" onClick={()=>{if(tour<TOUR.length-1){setTour(tour+1);go(TOUR[tour+1][0])}else notify("Guide tour completed.")}}>{tour===TOUR.length-1?"Finish":"Next"} <ChevronRight size={15}/></button></div></div>{modal&&<Modal k={modal}/>} {toast&&<div className="toast">{toast}</div>}</div>;
}
