import React,{useMemo,useState}from"react";
import HowWorks from "../how-works.jsx";
import{LayoutDashboard,Package,Layers,Boxes,CalendarClock,ArrowLeftRight,BarChart3,Settings,Menu,LogOut,Plus,Search,Trash2,CheckCircle2,Save,X,ChevronRight,Download,ArrowDownToLine,ArrowUpFromLine,AlertTriangle,Edit3}from"lucide-react";
import"./inventory.css";

const BRAND={name:"TechTarn",website:"www.techtarn.com",phone:"+90 - 7453966757",email:"contact@techtarn.com"};
const PANELS=["Super Admin","Management / CEO","Sales & CRM","Purchase","Production","Quality / QA-QC","Raw Material / Inventory","Warehouse","Food Safety","Maintenance","Machine Operator","Finance & Accounts","HR & Payroll","Logistics / Distribution","Reports & Analytics"];
const DATA={
stock:[
{id:"STK-1001",item:"Tomato Paste",sku:"RM-TOM-001",warehouse:"Main Store",qty:"2,450",uom:"kg",reserved:"600",available:"1,850",status:"Available"},
{id:"STK-1002",item:"Mango Pulp",sku:"RM-MAN-002",warehouse:"Cold Store",qty:"1,280",uom:"kg",reserved:"400",available:"880",status:"Available"},
{id:"STK-1003",item:"Sugar",sku:"RM-SUG-003",warehouse:"Dry Store",qty:"5,600",uom:"kg",reserved:"1,200",available:"4,400",status:"Available"},
{id:"STK-1004",item:"Citric Acid",sku:"RM-CIT-004",warehouse:"Chemical Store",qty:"320",uom:"kg",reserved:"80",available:"240",status:"Low Stock"}],
lots:[
{id:"LOT-2001",item:"Tomato Paste",lot:"TP-260901",supplier:"Agro Foods Ltd.",received:"2026-09-01",qty:"1,200",uom:"kg",expiry:"2027-03-01",status:"Released"},
{id:"LOT-2002",item:"Mango Pulp",lot:"MP-260902",supplier:"Fresh Harvest Co.",received:"2026-09-02",qty:"800",uom:"kg",expiry:"2026-12-15",status:"Released"},
{id:"LOT-2003",item:"Citric Acid",lot:"CA-260801",supplier:"ChemSupply Pvt. Ltd.",received:"2026-08-01",qty:"320",uom:"kg",expiry:"2026-10-20",status:"Quarantine"}],
batches:[
{id:"BCH-3001",item:"Tomato Paste",lot:"TP-260901",batch:"B-TP-001",qty:"600",uom:"kg",production:"2026-09-28",expiry:"2027-03-01",status:"Allocated"},
{id:"BCH-3002",item:"Mango Pulp",lot:"MP-260902",batch:"B-MP-001",qty:"400",uom:"kg",production:"2026-09-29",expiry:"2026-12-15",status:"Allocated"},
{id:"BCH-3003",item:"Sugar",lot:"SG-260903",batch:"B-SG-001",qty:"1,200",uom:"kg",production:"2026-09-30",expiry:"2028-09-30",status:"Available"}],
expiry:[
{id:"EXP-4001",item:"Citric Acid",lot:"CA-260801",expiry:"2026-10-20",qty:"320",uom:"kg",days:"25",risk:"Critical"},
{id:"EXP-4002",item:"Mango Pulp",lot:"MP-260902",expiry:"2026-12-15",qty:"800",uom:"kg",days:"81",risk:"Watch"},
{id:"EXP-4003",item:"Tomato Paste",lot:"TP-260901",expiry:"2027-03-01",qty:"1,200",uom:"kg",days:"157",risk:"Normal"}],
transfers:[
{id:"TRF-5001",item:"Tomato Paste",lot:"TP-260901",from:"Main Store",to:"Production Store",qty:"300",uom:"kg",date:"2026-09-28",status:"Completed"},
{id:"TRF-5002",item:"Mango Pulp",lot:"MP-260902",from:"Cold Store",to:"Production Store",qty:"200",uom:"kg",date:"2026-09-29",status:"In Transit"},
{id:"TRF-5003",item:"Sugar",lot:"SG-260903",from:"Dry Store",to:"Production Store",qty:"500",uom:"kg",date:"2026-09-30",status:"Draft"}]
};
const EMPTY={
stock:{item:"",sku:"",warehouse:"",qty:"",uom:"kg",reserved:"0",available:"",status:"Available"},
lots:{item:"",lot:"",supplier:"",received:"",qty:"",uom:"kg",expiry:"",status:"Released"},
batches:{item:"",lot:"",batch:"",qty:"",uom:"kg",production:"",expiry:"",status:"Available"},
expiry:{item:"",lot:"",expiry:"",qty:"",uom:"kg",days:"",risk:"Watch"},
transfers:{item:"",lot:"",from:"",to:"",qty:"",uom:"kg",date:"",status:"Draft"}
};
const TOUR=[["Dashboard","Review stock health, expiry risks and transfer activity."],["Stock","Check on-hand, reserved and available quantities."],["Lots","Track supplier lots, receipt dates and release status."],["Batches","Manage traceable inventory batches linked to lots."],["Expiry","Identify materials approaching expiry and prioritize action."],["Transfers","Create and complete warehouse-to-warehouse movements."],["Reports","Export inventory summaries and movement reports."],["Settings","Save inventory operating preferences."]];

export default function App(){
const[logged,setLogged]=useState(true),[email,setEmail]=useState("inventory@techtarn.com"),[password,setPassword]=useState("Demo@123"),[panel,setPanel]=useState("Raw Material / Inventory"),[tab,setTab]=useState("Dashboard"),[mobile,setMobile]=useState(false),[query,setQuery]=useState(""),[data,setData]=useState(DATA),[modal,setModal]=useState(null),[form,setForm]=useState(null),[toast,setToast]=useState(""),[tour,setTour]=useState(0);
const nav=[["Dashboard",LayoutDashboard],["Stock",Package],["Lots",Layers],["Batches",Boxes],["Expiry",CalendarClock],["Transfers",ArrowLeftRight],["Reports",BarChart3],["Settings",Settings]];
const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)},go=n=>{setTab(n);setMobile(false)},show=k=>{setModal(k);setForm({...EMPTY[k]})},close=()=>{setModal(null);setForm(null)};
const filtered=k=>data[k].filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
const add=k=>{const p={stock:"STK",lots:"LOT",batches:"BCH",expiry:"EXP",transfers:"TRF"}[k];const id=`${p}-${String(data[k].length+1).padStart(4,"0")}`;let row={id,...form};if(k==="stock"&&!row.available)row.available=String(Math.max(0,(Number(row.qty)||0)-(Number(row.reserved)||0)));setData({...data,[k]:[row,...data[k]]});close();notify("Record saved successfully.")};
const del=(k,id)=>{setData({...data,[k]:data[k].filter(r=>r.id!==id)});notify("Record deleted.")};
const status=(k,id,s)=>{setData({...data,[k]:data[k].map(r=>r.id===id?{...r,status:s}:r)});notify(`Status updated to ${s}.`)};
const login=e=>{e.preventDefault();if((email==="inventory@techtarn.com"||email==="admin@techtarn.com")&&password==="Demo@123")setLogged(true);else notify("Use the demo credentials.")};
if(!logged)return <div className="login"><div className="loginCard"><div className="brand"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="loginTitle"><h1>Raw Material / Inventory</h1><p>Stock • Lots • Batches • Expiry • Transfers</p></div><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Panel<select value={panel} onChange={e=>setPanel(e.target.value)}>{PANELS.map(x=><option key={x}>{x}</option>)}</select></label><button className="primary wide">Login <ChevronRight size={17}/></button></form><div className="demo">Demo: inventory@techtarn.com / Demo@123</div></div></div>;

const counts={stock:data.stock.length,lots:data.lots.length,batches:data.batches.length,expiry:data.expiry.filter(x=>x.risk!=="Normal").length,transfers:data.transfers.filter(x=>x.status!=="Completed").length};
const Table=({k,cols})=><div className="tableWrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}<th>Actions</th></tr></thead><tbody>{filtered(k).map(r=><tr key={r.id}>{cols.map(c=><td key={c[0]}>{c[0]==="status"||c[0]==="risk"?<span className={`badge ${String(r[c[0]]).toLowerCase().replaceAll(" ","-")}`}>{r[c[0]]}</span>:r[c[0]]}</td>)}<td className="actions">{(k==="transfers"&&r.status!=="Completed")&&<button className="iconBtn" title="Complete transfer" onClick={()=>status(k,r.id,"Completed")}><CheckCircle2 size={15}/></button>}{k==="lots"&&r.status==="Quarantine"&&<button className="iconBtn" title="Release lot" onClick={()=>status(k,r.id,"Released")}><CheckCircle2 size={15}/></button>}{k==="expiry"&&r.risk==="Critical"&&<button className="iconBtn" title="Mark reviewed" onClick={()=>status("expiry",r.id,"Normal")}><CheckCircle2 size={15}/></button>}<button className="iconBtn danger" title="Delete" onClick={()=>del(k,r.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>;

const moduleView=(title,sub,k,cols,addLabel)=><><div className="hero compact"><div><p className="eyebrow">RAW MATERIAL / INVENTORY</p><h1>{title}</h1><p>{sub}</p></div><button className="primary" onClick={()=>show(k)}><Plus size={17}/>{addLabel}</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered(k).length} record(s)</span></div><div className="card"><Table k={k} cols={cols}/></div></>;

const content=()=>{
if(tab==="Dashboard")return <><div className="hero"><div><p className="eyebrow">INVENTORY CONTROL CENTER</p><h1>Raw Material / Inventory Dashboard</h1><p>Track stock, traceability, expiry exposure and internal material movements.</p></div><button className="primary" onClick={()=>show("stock")}><Plus size={17}/> New Stock Item</button></div><div className="stats">{[["Stock Items",counts.stock,Package,"Stock"],["Lots",counts.lots,Layers,"Lots"],["Batches",counts.batches,Boxes,"Batches"],["Expiry Alerts",counts.expiry,CalendarClock,"Expiry"]].map(([l,v,I,t])=><div className="stat" key={l}><div className="statIcon"><I size={18}/></div><div><span>{l}</span><strong>{v}</strong></div><button onClick={()=>go(t)}>Open</button></div>)}</div><div className="grid2"><div className="card"><div className="cardHead"><div><h3>Inventory workflow</h3><p>Maintain traceability from receipt to transfer.</p></div></div>{["Stock availability","Lot traceability","Batch allocation","Expiry review","Transfer control"].map((x,i)=><div className="workflow" key={x}><b>{i+1}</b><span>{x}</span><ChevronRight size={16}/></div>)}</div><div className="card"><div className="cardHead"><div><h3>Attention required</h3><p>Current inventory exceptions.</p></div></div><div className="alert"><AlertTriangle size={17}/><span><b>{counts.expiry}</b> expiry item(s) need attention</span></div><div className="alert"><AlertTriangle size={17}/><span><b>{data.stock.filter(x=>x.status==="Low Stock").length}</b> low-stock item(s)</span></div><div className="alert"><ArrowLeftRight size={17}/><span><b>{counts.transfers}</b> transfer(s) not completed</span></div></div></div></>;
if(tab==="Stock")return moduleView("Stock","Maintain on-hand, reserved and available raw-material quantities.","stock",[["id","Stock ID"],["item","Item"],["sku","SKU"],["warehouse","Warehouse"],["qty","Qty"],["uom","UOM"],["reserved","Reserved"],["available","Available"],["status","Status"]],"Add Stock");
if(tab==="Lots")return moduleView("Lots","Track supplier lots, receipt dates, quantities and release status.","lots",[["id","Lot ID"],["item","Item"],["lot","Lot No."],["supplier","Supplier"],["received","Received"],["qty","Qty"],["uom","UOM"],["expiry","Expiry"],["status","Status"]],"Add Lot");
if(tab==="Batches")return moduleView("Batches","Maintain batch-level traceability and production allocation.","batches",[["id","Record ID"],["item","Item"],["lot","Lot No."],["batch","Batch No."],["qty","Qty"],["uom","UOM"],["production","Production"],["expiry","Expiry"],["status","Status"]],"Add Batch");
if(tab==="Expiry")return moduleView("Expiry","Monitor materials approaching expiry and review risk.","expiry",[["id","Alert ID"],["item","Item"],["lot","Lot No."],["expiry","Expiry"],["qty","Qty"],["uom","UOM"],["days","Days Left"],["risk","Risk"]],"Add Expiry Alert");
if(tab==="Transfers")return moduleView("Transfers","Move traceable raw materials between inventory locations.","transfers",[["id","Transfer ID"],["item","Item"],["lot","Lot No."],["from","From"],["to","To"],["qty","Qty"],["uom","UOM"],["date","Date"],["status","Status"]],"Create Transfer");
if(tab==="Reports")return <><div className="hero compact"><div><p className="eyebrow">REPORTING</p><h1>Inventory Reports</h1><p>Review stock, lot, batch, expiry and movement summaries.</p></div><button className="secondary" onClick={()=>notify("Inventory report export prepared.")}><Download size={17}/> Export Report</button></div><div className="reportGrid">{[["Stock Items",counts.stock,"Tracked inventory records"],["Lots",counts.lots,"Traceable supplier lots"],["Batches",counts.batches,"Allocated/available batches"],["Expiry Alerts",counts.expiry,"Items requiring review"],["Open Transfers",counts.transfers,"Movements not completed"]].map(([a,b,c])=><div className="reportCard" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small><div className="bar"><i style={{width:`${Math.min(100,Math.max(12,b*18))}%`}}/></div></div>)}</div></>;
return <div className="card settings"><div className="cardHead"><div><h2>Inventory Settings</h2><p>Configure operating preferences for this prototype.</p></div></div><div className="formGrid"><label>Default Warehouse<input defaultValue="Main Store"/></label><label>Expiry Alert Window<select defaultValue="90 days"><option>30 days</option><option>60 days</option><option>90 days</option></select></label><label>Stock Valuation<select defaultValue="FIFO"><option>FIFO</option><option>Weighted Average</option></select></label><label>Transfer Approval<select defaultValue="Supervisor"><option>Supervisor</option><option>Manager</option></select></label></div><button className="primary" onClick={()=>notify("Settings saved successfully.")}><Save size={17}/> Save Settings</button></div>;
};

const fields={stock:["item","sku","warehouse","qty","uom","reserved","available","status"],lots:["item","lot","supplier","received","qty","uom","expiry","status"],batches:["item","lot","batch","qty","uom","production","expiry","status"],expiry:["item","lot","expiry","qty","uom","days","risk"],transfers:["item","lot","from","to","qty","uom","date","status"]};
const titles={stock:"Add Stock Item",lots:"Add Lot",batches:"Add Batch",expiry:"Add Expiry Alert",transfers:"Create Transfer"};
const options={status:{stock:["Available","Low Stock","Blocked"],lots:["Released","Quarantine","Blocked"],batches:["Available","Allocated","Blocked"],transfers:["Draft","In Transit","Completed"]},risk:["Normal","Watch","Critical"]};
const Modal=({k})=><div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><div><h2>{titles[k]}</h2><p>Enter the required inventory data and save the record.</p></div><button className="iconBtn" onClick={close}><X size={18}/></button></div><div className="formGrid">{fields[k].map(f=><label key={f}>{f==="uom"?"UOM":f.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())}{f==="status"?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{options.status[k].map(o=><option key={o}>{o}</option>)}</select>:f==="risk"?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{options.risk.map(o=><option key={o}>{o}</option>)}</select>:<input required value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})} type={["received","expiry","production","date"].includes(f)?"date":"text"} placeholder={`Enter ${f}`}/>}</label>)}</div><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>add(k)}><Save size={17}/> Save Record</button></div></div></div>;

return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand side"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="panelTag">Raw Material / Inventory</div><nav>{nav.map(([n,I])=><button key={n} className={tab===n?"nav active":"nav"} onClick={()=>go(n)}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideFoot"><span>Logged in as</span><b>{email}</b><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></aside><main><header><button className="menuBtn" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div><b>{tab}</b><span>Raw Material / Inventory Panel</span></div><div className="headRight"><span>{BRAND.website}</span><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></header><section className="main">{content()}</section><HowWorks panel="Raw Material / Inventory" module={tab}/></main><div className="tour"><div><b>Guide Tour · {tour+1}/{TOUR.length}</b><span>{TOUR[tour][0]} — {TOUR[tour][1]}</span></div><div className="tourBtns"><button disabled={tour===0} onClick={()=>setTour(Math.max(0,tour-1))}>Back</button><button className="primary" onClick={()=>{if(tour<TOUR.length-1){setTour(tour+1);go(TOUR[tour+1][0])}else notify("Guide tour completed.")}}>{tour===TOUR.length-1?"Finish":"Next"} <ChevronRight size={15}/></button></div></div>{modal&&<Modal k={modal}/>} {toast&&<div className="toast">{toast}</div>}</div>;
}
