import React,{useState}from"react";import"./logistics-distribution.css";
import HowWorks from "../how-works.jsx";
const BRAND={name:"TechTarn",website:"www.techtarn.com",phone:"+90 - 7453966757",email:"contact@techtarn.com"};
const users=[["logistics@techtarn.com","Demo@123","Logistics Manager"],["admin@techtarn.com","Demo@123","Super Administrator"]];
const seed={vehicles:[
{id:"VEH-1001",reg:"UP15 AB 1024",type:"Refrigerated Truck",capacity:"12,000 kg",driver:"Rakesh Kumar",status:"Available"},
{id:"VEH-1002",reg:"UP15 CD 2048",type:"Delivery Van",capacity:"3,000 kg",driver:"Amit Singh",status:"On Route"},
{id:"VEH-1003",reg:"UP15 EF 3096",type:"Refrigerated Truck",capacity:"10,000 kg",driver:"Sanjay Verma",status:"Maintenance"},
{id:"VEH-1004",reg:"UP15 GH 4112",type:"Container Truck",capacity:"18,000 kg",driver:"Vikram Yadav",status:"Available"}],
routes:[
{id:"RTE-2001",name:"Delhi NCR Morning",origin:"Meerut Plant",destination:"Delhi NCR",distance:"112 km",stops:6,status:"Active"},
{id:"RTE-2002",name:"Ghaziabad Retail",origin:"Meerut Plant",destination:"Ghaziabad",distance:"78 km",stops:4,status:"Active"},
{id:"RTE-2003",name:"Noida Cold Chain",origin:"Cold Store",destination:"Noida",distance:"96 km",stops:5,status:"Active"}],
deliveries:[
{id:"DEL-3001",order:"SO-50021",customer:"FreshMart Delhi",route:"Delhi NCR Morning",vehicle:"UP15 AB 1024",date:"2026-09-25",status:"Dispatched"},
{id:"DEL-3002",order:"SO-50022",customer:"GreenBasket Ghaziabad",route:"Ghaziabad Retail",vehicle:"UP15 CD 2048",date:"2026-09-25",status:"In Transit"},
{id:"DEL-3003",order:"SO-50023",customer:"City Foods Noida",route:"Noida Cold Chain",vehicle:"UP15 EF 3096",date:"2026-09-26",status:"Planned"}],
transport:[
{id:"TRN-4001",delivery:"DEL-3001",carrier:"TechTarn Fleet",vehicle:"UP15 AB 1024",driver:"Rakesh Kumar",freight:8500,status:"Booked"},
{id:"TRN-4002",delivery:"DEL-3002",carrier:"TechTarn Fleet",vehicle:"UP15 CD 2048",driver:"Amit Singh",freight:6200,status:"In Transit"},
{id:"TRN-4003",delivery:"DEL-3003",carrier:"NorthLine Logistics",vehicle:"UP15 EF 3096",driver:"Sanjay Verma",freight:7100,status:"Pending"}],
pod:[
{id:"POD-5001",delivery:"DEL-3001",customer:"FreshMart Delhi",delivered:"2026-09-25 15:20",receivedBy:"Neha Gupta",condition:"Good",status:"Signed"},
{id:"POD-5002",delivery:"DEL-3002",customer:"GreenBasket Ghaziabad",delivered:"2026-09-25 18:05",receivedBy:"Karan Jain",condition:"Good",status:"Signed"},
{id:"POD-5003",delivery:"DEL-3003",customer:"City Foods Noida",delivered:"",receivedBy:"",condition:"",status:"Pending"}]};
const mods=[["dashboard","Dashboard"],["vehicles","Vehicles"],["routes","Routes"],["delivery","Delivery"],["transport","Transport"],["pod","POD"],["reports","Reports"],["settings","Settings"]];
const clone=x=>JSON.parse(JSON.stringify(x));const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2});
function Badge({children}){return <span className={"badge "+String(children).toLowerCase().replaceAll(" ","-")}>{children}</span>}
function Login({ok}){const[e,setE]=useState("logistics@techtarn.com"),[p,setP]=useState("Demo@123"),[err,setErr]=useState("");return <div className="login"><div className="login-card"><div className="logo">T</div><div className="eyebrow">FOOD PROCESSING ERP</div><h1>{BRAND.name}</h1><p>Logistics / Distribution workspace</p><form onSubmit={x=>{x.preventDefault();const u=users.find(a=>a[0]===e&&a[1]===p);u?ok({email:u[0],role:u[2]}):setErr("Invalid demo credentials.")}}><label>Email<input type="email" value={e} onChange={x=>setE(x.target.value)} required/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} required/></label>{err&&<div className="error">{err}</div>}<button className="primary full">Sign in</button></form><div className="demo"><b>Demo:</b> logistics@techtarn.com / Demo@123<br/>admin@techtarn.com / Demo@123</div></div></div>}
export default function App(){const[u,setU]=useState({email:"admin@techtarn.com",role:"Super Administrator"}),[d,setD]=useState(clone(seed)),[page,setPage]=useState("dashboard"),[mobile,setMobile]=useState(false),[toast,setToast]=useState(""),[tour,setTour]=useState(true),[ti,setTi]=useState(0);if(!u)return <Login ok={setU}/>;const notify=m=>{setToast(m);setTimeout(()=>setToast(""),1700)},upd=(k,v)=>setD(x=>({...x,[k]:v}));return <div className="app"><aside className={"side "+(mobile?"open":"")}><div className="sidebrand"><div className="logo sm">T</div><div><b>{BRAND.name}</b><small>Logistics / Distribution</small></div></div><nav>{mods.map(([id,n])=><button className={page===id?"active":""} key={id} onClick={()=>{setPage(id);setMobile(false)}}><span>{ico(id)}</span>{n}</button>)}</nav><div className="sidefoot"><small>{u.role}</small><button onClick={()=>setU(null)}>Sign out</button></div></aside>{mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>}<main><header><button className="hamb" onClick={()=>setMobile(!mobile)}>☰</button><b>Logistics / Distribution</b><span>/ {mods.find(x=>x[0]===page)[1]}</span><div className="user">{u.email}</div></header><section className="content">{page==="dashboard"?<Dashboard d={d} go={setPage}/>:page==="vehicles"?<Vehicles rows={d.vehicles} set={v=>upd("vehicles",v)} notify={notify}/>:page==="routes"?<Routes rows={d.routes} set={v=>upd("routes",v)} notify={notify}/>:page==="delivery"?<Delivery rows={d.deliveries} set={v=>upd("deliveries",v)} routes={d.routes} vehicles={d.vehicles} notify={notify}/>:page==="transport"?<Transport rows={d.transport} set={v=>upd("transport",v)} deliveries={d.deliveries} vehicles={d.vehicles} notify={notify}/>:page==="pod"?<POD rows={d.pod} set={v=>upd("pod",v)} deliveries={d.deliveries} notify={notify}/>:page==="reports"?<Reports d={d} notify={notify}/>:<Settings notify={notify}/>}</section><HowWorks panel="Logistics / Distribution" module={page}/></main>{toast&&<div className="toast">{toast}</div>}{tour&&<Tour i={ti} setI={setTi} close={()=>setTour(false)} go={setPage}/>}</div>}
function ico(id){return({dashboard:"⌂",vehicles:"▣",routes:"↗",delivery:"▰",transport:"⇄",pod:"✓",reports:"▤",settings:"⚙"})[id]}
function Dashboard({d,go}){const onroute=d.deliveries.filter(x=>["Dispatched","In Transit"].includes(x.status)).length,pending=d.deliveries.filter(x=>x.status==="Planned").length,pods=d.pod.filter(x=>x.status==="Pending").length,maint=d.vehicles.filter(x=>x.status==="Maintenance").length;return <><div className="hero"><div><div className="eyebrow light">DISTRIBUTION CONTROL</div><h2>Logistics & Delivery Control Center</h2><p>Manage fleet, routes, deliveries, transport and proof of delivery.</p></div><button className="lightbtn" onClick={()=>go("delivery")}>Manage Deliveries</button></div><div className="stats">{[["Vehicles",d.vehicles.length,"vehicles"],["On Route",onroute,"delivery"],["Planned",pending,"delivery"],["POD Pending",pods,"pod"],["Maintenance",maint,"vehicles"]].map(x=><button className="stat" key={x[0]} onClick={()=>go(x[2])}><span>{x[0]}</span><strong>{x[1]}</strong><small>Open module →</small></button>)}</div><div className="grid2"><Panel title="Fleet Status"><Metric label="Available" value={d.vehicles.filter(x=>x.status==="Available").length}/><Metric label="On Route" value={d.vehicles.filter(x=>x.status==="On Route").length}/><Metric label="Maintenance" value={maint}/></Panel><Panel title="Delivery Status"><Metric label="Dispatched / Transit" value={onroute}/><Metric label="Planned" value={pending}/><Metric label="POD Pending" value={pods}/></Panel></div></>}
function Panel({title,children}){return <div className="panel"><div className="ptitle"><h3>{title}</h3></div><div className="pbody">{children}</div></div>}function Metric({label,value}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}
function Table({headers,rows,render}){return <div className="table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(render):<tr><td className="empty" colSpan={headers.length}>No records found</td></tr>}</tbody></table></div>}
function Modal({title,close,children}){return <div className="modalbg" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="mhead"><h3>{title}</h3><button onClick={close}>×</button></div>{children}</div></div>}
function Form({fields,initial,onSave,onCancel}){const[v,setV]=useState(()=>Object.fromEntries(fields.map(f=>[f.n,initial[f.n]??f.def??""]))),[err,setErr]=useState("");return <form className="form" onSubmit={e=>{e.preventDefault();const f=fields.find(x=>x.req&&!String(v[x.n]??"").trim());if(f){setErr(f.l+" is required.");return}try{onSave(v)}catch(x){setErr(x.message)}}}>{fields.map(f=><label key={f.n}>{f.l}{f.req&&<em>*</em>}{f.t==="select"?<select value={v[f.n]} onChange={e=>setV({...v,[f.n]:e.target.value})}><option value="">Select...</option>{f.o.map(o=><option key={o}>{o}</option>)}</select>:<input type={f.t||"text"} min={f.min} step={f.step} value={v[f.n]} onChange={e=>setV({...v,[f.n]:e.target.value})}/>}</label>)}{err&&<div className="error">{err}</div>}<div className="actions"><button type="button" onClick={onCancel}>Cancel</button><button className="primary">Save</button></div></form>}
function CRUD({title,sub,rows,set,fields,search,heads,render,make,notify,label}){const[q,setQ]=useState(""),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),filtered=rows.filter(r=>search.some(k=>String(r[k]??"").toLowerCase().includes(q.toLowerCase())));const save=v=>{const r=make(v,edit);set(edit?rows.map(x=>x.id===edit.id?r:x):[r,...rows]);setOpen(false);setEdit(null);notify(edit?"Record updated":"Record added")};return <><div className="pagehead"><div><div className="eyebrow">MASTER / TRANSACTION</div><h2>{title}</h2><p>{sub}</p></div><button className="primary" onClick={()=>{setEdit(null);setOpen(true)}}>+ {label}</button></div><div className="toolbar"><input placeholder="Search..." value={q} onChange={e=>setQ(e.target.value)}/><span>{filtered.length} records</span></div><Panel title={title+" List"}><Table headers={[...heads,"Actions"]} rows={filtered} render={r=><tr key={r.id}>{render(r)}<td className="rowactions"><button onClick={()=>{setEdit(r);setOpen(true)}}>Edit</button><button className="danger" onClick={()=>{if(confirm("Delete this record?")){set(rows.filter(x=>x.id!==r.id));notify("Record deleted")}}}>Delete</button></td></tr>}/></Panel>{open&&<Modal title={(edit?"Edit ":"Add ")+title} close={()=>{setOpen(false);setEdit(null)}}><Form fields={fields} initial={edit||{}} onSave={save} onCancel={()=>{setOpen(false);setEdit(null)}}/></Modal>}</>}
function Vehicles({rows,set,notify}){const f=[{n:"reg",l:"Registration No.",req:true},{n:"type",l:"Vehicle Type",t:"select",o:["Refrigerated Truck","Delivery Van","Container Truck","Pickup"],req:true},{n:"capacity",l:"Capacity",req:true},{n:"driver",l:"Driver",req:true},{n:"status",l:"Status",t:"select",o:["Available","On Route","Maintenance","Inactive"],req:true}];return <CRUD title="Vehicles" sub="Maintain fleet, capacity, drivers and availability." rows={rows} set={set} search={["id","reg","type","driver","status"]} heads={["ID","Registration","Type","Capacity","Driver","Status"]} render={r=><><td>{r.id}</td><td><b>{r.reg}</b></td><td>{r.type}</td><td>{r.capacity}</td><td>{r.driver}</td><td><Badge>{r.status}</Badge></td></>} fields={f} make={(v,e)=>({...v,id:e?.id||"VEH-"+String(Date.now()).slice(-4)})} notify={notify} label="Vehicle"/>}
function Routes({rows,set,notify}){const f=[{n:"name",l:"Route Name",req:true},{n:"origin",l:"Origin",req:true},{n:"destination",l:"Destination",req:true},{n:"distance",l:"Distance",req:true},{n:"stops",l:"Stops",t:"number",min:1,step:1,req:true},{n:"status",l:"Status",t:"select",o:["Active","Inactive"],req:true}];return <CRUD title="Routes" sub="Define distribution routes, distances and delivery stops." rows={rows} set={set} search={["id","name","origin","destination","status"]} heads={["ID","Route","Origin","Destination","Distance","Stops","Status"]} render={r=><><td>{r.id}</td><td>{r.name}</td><td>{r.origin}</td><td>{r.destination}</td><td>{r.distance}</td><td>{r.stops}</td><td><Badge>{r.status}</Badge></td></>} fields={f} make={(v,e)=>({...v,stops:Number(v.stops),id:e?.id||"RTE-"+String(Date.now()).slice(-4)})} notify={notify} label="Route"/>}
function Delivery({rows,set,routes,vehicles,notify}){const f=[{n:"order",l:"Sales Order",req:true},{n:"customer",l:"Customer",req:true},{n:"route",l:"Route",t:"select",o:routes.map(x=>x.name),req:true},{n:"vehicle",l:"Vehicle",t:"select",o:vehicles.map(x=>x.reg),req:true},{n:"date",l:"Delivery Date",t:"date",req:true},{n:"status",l:"Status",t:"select",o:["Planned","Dispatched","In Transit","Delivered","Cancelled"],req:true}];return <CRUD title="Delivery" sub="Plan and track customer deliveries from dispatch to completion." rows={rows} set={set} search={["id","order","customer","route","vehicle","status"]} heads={["ID","Order","Customer","Route","Vehicle","Date","Status"]} render={r=><><td>{r.id}</td><td>{r.order}</td><td>{r.customer}</td><td>{r.route}</td><td>{r.vehicle}</td><td>{r.date}</td><td><Badge>{r.status}</Badge></td></>} fields={f} make={(v,e)=>({...v,id:e?.id||"DEL-"+String(Date.now()).slice(-4)})} notify={notify} label="Delivery"/>}
function Transport({rows,set,deliveries,vehicles,notify}){const f=[{n:"delivery",l:"Delivery",t:"select",o:deliveries.map(x=>x.id),req:true},{n:"carrier",l:"Carrier",req:true},{n:"vehicle",l:"Vehicle",t:"select",o:vehicles.map(x=>x.reg),req:true},{n:"driver",l:"Driver",req:true},{n:"freight",l:"Freight",t:"number",min:0,step:0.01,req:true},{n:"status",l:"Status",t:"select",o:["Pending","Booked","In Transit","Completed","Cancelled"],req:true}];return <CRUD title="Transport" sub="Manage carrier assignment, drivers, freight and transport status." rows={rows} set={set} search={["id","delivery","carrier","vehicle","driver","status"]} heads={["ID","Delivery","Carrier","Vehicle","Driver","Freight","Status"]} render={r=><><td>{r.id}</td><td>{r.delivery}</td><td>{r.carrier}</td><td>{r.vehicle}</td><td>{r.driver}</td><td>{money(r.freight)}</td><td><Badge>{r.status}</Badge></td></>} fields={f} make={(v,e)=>({...v,freight:Number(v.freight),id:e?.id||"TRN-"+String(Date.now()).slice(-4)})} notify={notify} label="Transport Entry"/>}
function POD({rows,set,deliveries,notify}){const f=[{n:"delivery",l:"Delivery",t:"select",o:deliveries.map(x=>x.id),req:true},{n:"customer",l:"Customer",req:true},{n:"delivered",l:"Delivered At",req:false},{n:"receivedBy",l:"Received By",req:false},{n:"condition",l:"Condition",t:"select",o:["Good","Damaged","Partial","Rejected"]},{n:"status",l:"POD Status",t:"select",o:["Pending","Signed","Exception"],req:true}];return <CRUD title="POD" sub="Capture proof of delivery, recipient and delivery condition." rows={rows} set={set} search={["id","delivery","customer","receivedBy","status"]} heads={["ID","Delivery","Customer","Delivered","Received By","Condition","Status"]} render={r=><><td>{r.id}</td><td>{r.delivery}</td><td>{r.customer}</td><td>{r.delivered||"—"}</td><td>{r.receivedBy||"—"}</td><td>{r.condition||"—"}</td><td><Badge>{r.status}</Badge></td></>} fields={f} make={(v,e)=>({...v,id:e?.id||"POD-"+String(Date.now()).slice(-4)})} notify={notify} label="POD Entry"/>}
function Reports({d,notify}){return <><div className="pagehead"><div><div className="eyebrow">ANALYTICS</div><h2>Reports</h2><p>Distribution and fleet summary reports.</p></div><button className="primary" onClick={()=>notify("Report export prepared")}>Export Report</button></div><div className="reportgrid">{[["Fleet Vehicles",d.vehicles.length],["Active Routes",d.routes.filter(x=>x.status==="Active").length],["Deliveries",d.deliveries.length],["In Transit",d.deliveries.filter(x=>x.status==="In Transit").length],["Transport Cost",money(d.transport.reduce((s,x)=>s+Number(x.freight||0),0))],["POD Pending",d.pod.filter(x=>x.status==="Pending").length]].map(x=><Panel key={x[0]} title={x[0]}><div className="big">{x[1]}</div></Panel>)}</div></>}
function Settings({notify}){return <><div className="pagehead"><div><div className="eyebrow">CONFIGURATION</div><h2>Settings</h2><p>Maintain logistics preferences.</p></div></div><Panel title="Distribution Settings"><div className="form settings"><label>Company Name<input defaultValue={BRAND.name}/></label><label>Distance Unit<select defaultValue="km"><option>km</option><option>mi</option></select></label><label>Default Delivery Priority<select defaultValue="Standard"><option>Standard</option><option>High</option><option>Critical</option></select></label><label>Temperature Tracking<select defaultValue="Enabled"><option>Enabled</option><option>Disabled</option></select></label><button className="primary" onClick={()=>notify("Settings saved successfully")}>Save Settings</button></div></Panel></>}
function Tour({i,setI,close,go}){const s=[["dashboard","Dashboard","Review fleet, route, delivery and POD attention items."],["vehicles","Vehicles","Add, edit and track fleet vehicles, capacity and drivers."],["routes","Routes","Maintain origin, destination, distance and stops."],["delivery","Delivery","Plan and track customer deliveries."],["transport","Transport","Assign carrier, vehicle, driver and freight."],["pod","POD","Capture proof of delivery and exceptions."],["reports","Reports","Review distribution summaries and export reports."],["settings","Settings","Maintain logistics configuration."]],x=s[i];return <div className="tour"><small>GUIDE TOUR · {i+1}/{s.length}</small><b>{x[1]}</b><p>{x[2]}</p><div className="touractions"><button disabled={!i} onClick={()=>{setI(i-1);go(s[i-1][0])}}>Back</button>{i<s.length-1?<button className="primary" onClick={()=>{setI(i+1);go(s[i+1][0])}}>Next</button>:<button className="primary" onClick={close}>Finish</button>}</div><button className="x" onClick={close}>×</button></div>}
