import React,{useState}from"react";
import HowWorks from "../how-works.jsx";
import{LayoutDashboard,Cpu,Factory,Timer,ClipboardCheck,BarChart3,Settings,Menu,LogOut,Plus,Search,Trash2,CheckCircle2,Save,X,ChevronRight,Download,AlertTriangle,Play,PauseCircle}from"lucide-react";
import"./machine-operator.css";
const BRAND={name:"TechTarn",website:"www.techtarn.com",phone:"+90 - 7453966757",email:"contact@techtarn.com"};
const PANELS=["Super Admin","Management / CEO","Sales & CRM","Purchase","Production","Quality / QA-QC","Raw Material / Inventory","Warehouse","Food Safety","Maintenance","Machine Operator","Finance & Accounts","HR & Payroll","Logistics / Distribution","Reports & Analytics"];
const DATA={
status:[{id:"MS-1001",machine:"Filling Machine 01",code:"FM-01",line:"Line A",shift:"Morning",operator:"Arun Kumar",status:"Running",updated:"2026-09-25 08:10"},{id:"MS-1002",machine:"Pasteurizer 01",code:"PAS-01",line:"Line A",shift:"Morning",operator:"Neha Singh",status:"Running",updated:"2026-09-25 08:25"},{id:"MS-1003",machine:"Packing Machine 02",code:"PK-02",line:"Line B",shift:"Night",operator:"Ravi Shah",status:"Stopped",updated:"2026-09-24 23:40"}],
production:[{id:"PE-2001",machine:"Filling Machine 01",order:"MO-260925-01",product:"Mango Juice 1L",batch:"B-260925-A",qty:"4200",uom:"Bottles",shift:"Morning",operator:"Arun Kumar",status:"Submitted"},{id:"PE-2002",machine:"Pasteurizer 01",order:"MO-260925-02",product:"Mixed Fruit Juice 500ml",batch:"B-260925-B",qty:"3100",uom:"Bottles",shift:"Morning",operator:"Neha Singh",status:"Draft"},{id:"PE-2003",machine:"Packing Machine 02",order:"MO-260924-09",product:"Tomato Sauce 500g",batch:"B-260924-C",qty:"1800",uom:"Pouches",shift:"Night",operator:"Ravi Shah",status:"Submitted"}],
downtime:[{id:"DT-3001",machine:"Filling Machine 01",reason:"Nozzle pressure fluctuation",start:"2026-09-25 10:15",end:"2026-09-25 10:45",minutes:"30",category:"Mechanical",action:"Nozzle cleaned and pressure reset",status:"Closed"},{id:"DT-3002",machine:"Packing Machine 02",reason:"Film feed jam",start:"2026-09-24 22:20",end:"2026-09-24 22:50",minutes:"30",category:"Material",action:"Film roll aligned",status:"Closed"},{id:"DT-3003",machine:"Pasteurizer 01",reason:"Temperature deviation",start:"2026-09-25 11:05",end:"",minutes:"0",category:"Process",action:"Under investigation",status:"Open"}],
checklist:[{id:"CL-4001",machine:"Filling Machine 01",shift:"Morning",date:"2026-09-25",item:"Emergency stop tested",result:"Pass",operator:"Arun Kumar",status:"Completed"},{id:"CL-4002",machine:"Filling Machine 01",shift:"Morning",date:"2026-09-25",item:"Guards and covers checked",result:"Pass",operator:"Arun Kumar",status:"Completed"},{id:"CL-4003",machine:"Pasteurizer 01",shift:"Morning",date:"2026-09-25",item:"Temperature display verified",result:"Pass",operator:"Neha Singh",status:"Completed"},{id:"CL-4004",machine:"Packing Machine 02",shift:"Night",date:"2026-09-24",item:"Film path and rollers checked",result:"Fail",operator:"Ravi Shah",status:"Attention"}]
};
const EMPTY={status:{machine:"",code:"",line:"",shift:"Morning",operator:"",status:"Running",updated:""},production:{machine:"",order:"",product:"",batch:"",qty:"",uom:"Bottles",shift:"Morning",operator:"",status:"Draft"},downtime:{machine:"",reason:"",start:"",end:"",minutes:"0",category:"Mechanical",action:"",status:"Open"},checklist:{machine:"",shift:"Morning",date:"",item:"",result:"Pass",operator:"",status:"Completed"}};
const TOUR=[["Dashboard","See live machine status, production output, downtime and checklist exceptions."],["Machine Status","Update the running state of the assigned machine and shift details."],["Production Entry","Enter production quantities, batch and manufacturing order details."],["Downtime","Record downtime reason, duration, category and corrective action."],["Checklist","Complete operator safety and pre-start checks with pass/fail results."],["Reports","Review operator activity and export the current shift summary."],["Settings","Save operator defaults for shift and workstation preferences."]];
export default function App(){
const[logged,setLogged]=useState(true),[email,setEmail]=useState("operator@techtarn.com"),[password,setPassword]=useState("Demo@123"),[panel,setPanel]=useState("Machine Operator"),[tab,setTab]=useState("Dashboard"),[mobile,setMobile]=useState(false),[query,setQuery]=useState(""),[data,setData]=useState(DATA),[modal,setModal]=useState(null),[form,setForm]=useState(null),[toast,setToast]=useState(""),[tour,setTour]=useState(0);
const nav=[["Dashboard",LayoutDashboard],["Machine Status",Cpu],["Production Entry",Factory],["Downtime",Timer],["Checklist",ClipboardCheck],["Reports",BarChart3],["Settings",Settings]];
const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)},go=n=>{setTab(n);setMobile(false);setQuery("")};
const show=k=>{setModal(k);setForm({...EMPTY[k]})},close=()=>{setModal(null);setForm(null)};
const filtered=k=>data[k].filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
const add=k=>{const p={status:"MS",production:"PE",downtime:"DT",checklist:"CL"}[k];const id=`${p}-${String(data[k].length+1).padStart(4,"0")}`;setData({...data,[k]:[{id,...form},...data[k]]});close();notify("Record saved successfully.")};
const del=(k,id)=>{setData({...data,[k]:data[k].filter(r=>r.id!==id)});notify("Record deleted.")};
const status=(k,id,s)=>{setData({...data,[k]:data[k].map(r=>r.id===id?{...r,status:s}:r)});notify(`Status updated to ${s}.`)};
const login=e=>{e.preventDefault();if((email==="operator@techtarn.com"||email==="admin@techtarn.com")&&password==="Demo@123")setLogged(true);else notify("Use the demo credentials.")};
if(!logged)return <div className="login"><div className="loginCard"><div className="brand"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="loginTitle"><h1>Machine Operator</h1><p>Machine Status • Production Entry • Downtime • Checklist</p></div><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Panel<select value={panel} onChange={e=>setPanel(e.target.value)}>{PANELS.map(x=><option key={x}>{x}</option>)}</select></label><button className="primary wide">Login <ChevronRight size={17}/></button></form><div className="demo">Demo: operator@techtarn.com / Demo@123</div></div></div>;
const counts={machines:data.status.filter(x=>x.status==="Running").length,production:data.production.reduce((s,x)=>s+(Number(x.qty)||0),0),downtime:data.downtime.filter(x=>x.status!=="Closed").length,checks:data.checklist.filter(x=>x.status!=="Completed").length};
const Table=({k,cols})=><div className="tableWrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}<th>Actions</th></tr></thead><tbody>{filtered(k).map(r=><tr key={r.id}>{cols.map(c=><td key={c[0]}>{["status","result"].includes(c[0])?<span className={`badge ${String(r[c[0]]).toLowerCase().replaceAll(" ","-")}`}>{r[c[0]]}</span>:r[c[0]]}</td>)}<td className="actions">{k==="status"&&<button className="iconBtn" title={r.status==="Running"?"Stop machine":"Start machine"} onClick={()=>status(k,r.id,r.status==="Running"?"Stopped":"Running")}>{r.status==="Running"?<PauseCircle size={15}/>:<Play size={15}/>}</button>}{k==="production"&&r.status==="Draft"&&<button className="iconBtn" title="Submit entry" onClick={()=>status(k,r.id,"Submitted")}><CheckCircle2 size={15}/></button>}{k==="downtime"&&r.status!=="Closed"&&<button className="iconBtn" title="Close downtime" onClick={()=>status(k,r.id,"Closed")}><CheckCircle2 size={15}/></button>}{k==="checklist"&&r.status!=="Completed"&&<button className="iconBtn" title="Complete checklist" onClick={()=>status(k,r.id,"Completed")}><CheckCircle2 size={15}/></button>}<button className="iconBtn danger" title="Delete" onClick={()=>del(k,r.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>;
const moduleView=(title,sub,k,cols,label)=><><div className="hero compact"><div><p className="eyebrow">MACHINE OPERATOR</p><h1>{title}</h1><p>{sub}</p></div><button className="primary" onClick={()=>show(k)}><Plus size={17}/>{label}</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered(k).length} record(s)</span></div><div className="card"><Table k={k} cols={cols}/></div></>;
const content=()=>{if(tab==="Dashboard")return <><div className="hero"><div><p className="eyebrow">SHOP FLOOR CONTROL</p><h1>Machine Operator Dashboard</h1><p>Capture machine status, production output, downtime and operator checks.</p></div><button className="primary" onClick={()=>show("production")}><Plus size={17}/> New Production Entry</button></div><div className="stats">{[["Machines Running",counts.machines,Cpu,"Machine Status"],["Units Recorded",counts.production,Factory,"Production Entry"],["Open Downtime",counts.downtime,Timer,"Downtime"],["Checklist Attention",counts.checks,ClipboardCheck,"Checklist"]].map(([l,v,I,t])=><div className="stat" key={l}><div className="statIcon"><I size={18}/></div><div><span>{l}</span><strong>{v}</strong></div><button onClick={()=>go(t)}>Open</button></div>)}</div><div className="grid2"><div className="card"><div className="cardHead"><div><h3>Operator workflow</h3><p>Complete the shift from machine start to production close.</p></div></div>{["Confirm machine status","Enter production output","Log downtime if any","Complete checklist"].map((x,i)=><div className="workflow" key={x}><b>{i+1}</b><span>{x}</span><ChevronRight size={16}/></div>)}</div><div className="card"><div className="cardHead"><div><h3>Attention required</h3><p>Items needing operator action.</p></div></div><div className="alert"><AlertTriangle size={17}/><span><b>{data.status.filter(x=>x.status!=="Running").length}</b> machine(s) not running</span></div><div className="alert"><AlertTriangle size={17}/><span><b>{data.downtime.filter(x=>x.status!=="Closed").length}</b> downtime record(s) open</span></div><div className="alert"><ClipboardCheck size={17}/><span><b>{data.checklist.filter(x=>x.status!=="Completed").length}</b> checklist item(s) need attention</span></div></div></div></>;
if(tab==="Machine Status")return moduleView("Machine Status","Update assigned equipment status and operator shift information.","status",[["id","Status ID"],["machine","Machine"],["code","Asset Code"],["line","Line"],["shift","Shift"],["operator","Operator"],["status","Status"],["updated","Updated"]],"Add Status");
if(tab==="Production Entry")return moduleView("Production Entry","Record manufacturing order, batch, quantity and shift output.","production",[["id","Entry ID"],["machine","Machine"],["order","Order"],["product","Product"],["batch","Batch"],["qty","Qty"],["uom","UOM"],["shift","Shift"],["operator","Operator"],["status","Status"]],"Add Production Entry");
if(tab==="Downtime")return moduleView("Downtime","Record stoppage reason, duration, category and corrective action.","downtime",[["id","Downtime ID"],["machine","Machine"],["reason","Reason"],["start","Start"],["end","End"],["minutes","Minutes"],["category","Category"],["action","Action"],["status","Status"]],"Log Downtime");
if(tab==="Checklist")return moduleView("Checklist","Complete operator pre-start and safety checks for the assigned machine.","checklist",[["id","Check ID"],["machine","Machine"],["shift","Shift"],["date","Date"],["item","Checklist Item"],["result","Result"],["operator","Operator"],["status","Status"]],"Add Checklist Item");
if(tab==="Reports")return <><div className="hero compact"><div><p className="eyebrow">SHIFT REPORTING</p><h1>Operator Reports</h1><p>Review production entries, machine status, downtime and checklist completion.</p></div><button className="secondary" onClick={()=>notify("Operator report export prepared.")}><Download size={17}/> Export Report</button></div><div className="reportGrid">{[["Running Machines",counts.machines,"Currently running"],["Units Recorded",counts.production,"Production quantity"],["Open Downtime",counts.downtime,"Needs closure"],["Checklist Attention",counts.checks,"Requires action"]].map(([a,b,c])=><div className="reportCard" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small><div className="bar"><i style={{width:`${Math.min(100,Math.max(12,Number(b)*12||12))}%`}}/></div></div>)}</div></>;
return <div className="card settings"><div className="cardHead"><div><h2>Machine Operator Settings</h2><p>Configure operator defaults for this prototype.</p></div></div><div className="formGrid"><label>Default Machine<input defaultValue="Filling Machine 01"/></label><label>Default Shift<select defaultValue="Morning"><option>Morning</option><option>Evening</option><option>Night</option></select></label><label>Operator Name<input defaultValue="Arun Kumar"/></label><label>Line<input defaultValue="Line A"/></label></div><button className="primary" onClick={()=>notify("Settings saved successfully.")}><Save size={17}/> Save Settings</button></div>};
const fields={status:["machine","code","line","shift","operator","status","updated"],production:["machine","order","product","batch","qty","uom","shift","operator","status"],downtime:["machine","reason","start","end","minutes","category","action","status"],checklist:["machine","shift","date","item","result","operator","status"]};
const titles={status:"Add Machine Status",production:"Add Production Entry",downtime:"Log Downtime",checklist:"Add Checklist Item"};
const opts={status:{status:["Running","Stopped","Idle"]},production:{status:["Draft","Submitted"]},downtime:{status:["Open","Closed"],category:["Mechanical","Electrical","Material","Process","Utility","Other"]},checklist:{result:["Pass","Fail","N/A"],status:["Completed","Attention"]}};
const Modal=({k})=><div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><div><h2>{titles[k]}</h2><p>Enter the operator data and save the record.</p></div><button className="iconBtn" onClick={close}><X size={18}/></button></div><div className="formGrid">{fields[k].map(f=><label key={f}>{f.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())}{opts[k]?.[f]?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{opts[k][f].map(o=><option key={o}>{o}</option>)}</select>:<input required value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})} type={f==="date"?"date":"text"} placeholder={`Enter ${f}`}/>}</label>)}</div><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>add(k)}><Save size={17}/> Save Record</button></div></div></div>;
return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand side"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="panelTag">Machine Operator</div><nav>{nav.map(([n,I])=><button key={n} className={tab===n?"nav active":"nav"} onClick={()=>go(n)}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideFoot"><span>Logged in as</span><b>{email}</b><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></aside><main><header><button className="menuBtn" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div><b>{tab}</b><span>Machine Operator Panel</span></div><div className="headRight"><span>{BRAND.website}</span><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></header><section className="main">{content()}</section><HowWorks panel="Machine Operator" module={tab}/></main><div className="tour"><div><b>Guide Tour · {tour+1}/{TOUR.length}</b><span>{TOUR[tour][0]} — {TOUR[tour][1]}</span></div><div className="tourBtns"><button disabled={tour===0} onClick={()=>setTour(Math.max(0,tour-1))}>Back</button><button className="primary" onClick={()=>{if(tour<TOUR.length-1){setTour(tour+1);go(TOUR[tour+1][0])}else notify("Guide tour completed.")}}>{tour===TOUR.length-1?"Finish":"Next"} <ChevronRight size={15}/></button></div></div>{modal&&<Modal k={modal}/>} {toast&&<div className="toast">{toast}</div>}</div>;
}
