import React,{useState}from"react";
import HowWorks from "../how-works.jsx";
import{LayoutDashboard,Cpu,CalendarCheck,AlertOctagon,PackageSearch,BarChart3,Settings,Menu,LogOut,Plus,Search,Trash2,CheckCircle2,Save,X,ChevronRight,Download,AlertTriangle,Wrench}from"lucide-react";
import"./maintenance.css";

const BRAND={name:"TechTarn",website:"www.techtarn.com",phone:"+90 - 7453966757",email:"contact@techtarn.com"};
const PANELS=["Super Admin","Management / CEO","Sales & CRM","Purchase","Production","Quality / QA-QC","Raw Material / Inventory","Warehouse","Food Safety","Maintenance","Machine Operator","Finance & Accounts","HR & Payroll","Logistics / Distribution","Reports & Analytics"];
const DATA={
machines:[
{id:"MAC-1001",machine:"Filling Machine 01",code:"FM-01",line:"Line A",location:"Production Hall",criticality:"High",lastService:"2026-09-10",status:"Running"},
{id:"MAC-1002",machine:"Pasteurizer 01",code:"PAS-01",line:"Line A",location:"Thermal Room",criticality:"Critical",lastService:"2026-09-05",status:"Running"},
{id:"MAC-1003",machine:"Cold Room Compressor",code:"CRC-01",line:"Cold Store",location:"Cold Warehouse",criticality:"Critical",lastService:"2026-08-28",status:"Maintenance Due"},
{id:"MAC-1004",machine:"Packing Machine 02",code:"PK-02",line:"Line B",location:"Packing Hall",criticality:"Medium",lastService:"2026-09-18",status:"Running"}],
pm:[
{id:"PM-2001",machine:"Filling Machine 01",asset:"FM-01",task:"Lubrication & inspection",frequency:"Monthly",due:"2026-10-01",technician:"Maintenance Team A",status:"Scheduled"},
{id:"PM-2002",machine:"Pasteurizer 01",asset:"PAS-01",task:"Temperature sensor calibration",frequency:"Quarterly",due:"2026-10-05",technician:"Maintenance Team B",status:"In Progress"},
{id:"PM-2003",machine:"Cold Room Compressor",asset:"CRC-01",task:"Compressor service",frequency:"Monthly",due:"2026-09-30",technician:"Maintenance Team A",status:"Overdue"}],
breakdowns:[
{id:"BD-3001",machine:"Cold Room Compressor",asset:"CRC-01",issue:"High discharge temperature",reported:"2026-09-25 08:40",priority:"Critical",technician:"Maintenance Team A",downtime:"3.5 hrs",status:"In Progress"},
{id:"BD-3002",machine:"Packing Machine 02",asset:"PK-02",issue:"Film feed jam",reported:"2026-09-26 11:15",priority:"High",technician:"Maintenance Team B",downtime:"1.2 hrs",status:"Resolved"},
{id:"BD-3003",machine:"Filling Machine 01",asset:"FM-01",issue:"Nozzle pressure fluctuation",reported:"2026-09-27 14:05",priority:"Medium",technician:"Maintenance Team A",downtime:"0.8 hrs",status:"Open"}],
spares:[
{id:"SPR-4001",part:"Filling Nozzle Seal Kit",sku:"SP-FM-001",machine:"Filling Machine 01",qty:"24",min:"10",uom:"set",location:"Maintenance Store",status:"Available"},
{id:"SPR-4002",part:"Temperature Sensor",sku:"SP-PAS-002",machine:"Pasteurizer 01",qty:"6",min:"4",uom:"pcs",location:"Maintenance Store",status:"Available"},
{id:"SPR-4003",part:"Compressor Belt",sku:"SP-CRC-003",machine:"Cold Room Compressor",qty:"2",min:"3",uom:"pcs",location:"Maintenance Store",status:"Low Stock"},
{id:"SPR-4004",part:"Film Feed Roller",sku:"SP-PK-004",machine:"Packing Machine 02",qty:"8",min:"2",uom:"pcs",location:"Maintenance Store",status:"Available"}]
};
const EMPTY={
machines:{machine:"",code:"",line:"",location:"",criticality:"Medium",lastService:"",status:"Running"},
pm:{machine:"",asset:"",task:"",frequency:"Monthly",due:"",technician:"",status:"Scheduled"},
breakdowns:{machine:"",asset:"",issue:"",reported:"",priority:"Medium",technician:"",downtime:"0",status:"Open"},
spares:{part:"",sku:"",machine:"",qty:"",min:"",uom:"pcs",location:"",status:"Available"}
};
const TOUR=[["Dashboard","Review asset health, PM workload, breakdowns and spare stock."],["Machines","Maintain equipment master data, criticality and service status."],["Preventive Maintenance","Schedule recurring maintenance tasks and track completion."],["Breakdown","Log failures, assign technicians and close breakdowns."],["Spares","Track maintenance spare quantities and low-stock items."],["Reports","Export maintenance performance summaries."],["Settings","Save maintenance operating preferences."]];

export default function App(){
const[logged,setLogged]=useState(true),[email,setEmail]=useState("maintenance@techtarn.com"),[password,setPassword]=useState("Demo@123"),[panel,setPanel]=useState("Maintenance"),[tab,setTab]=useState("Dashboard"),[mobile,setMobile]=useState(false),[query,setQuery]=useState(""),[data,setData]=useState(DATA),[modal,setModal]=useState(null),[form,setForm]=useState(null),[toast,setToast]=useState(""),[tour,setTour]=useState(0);
const nav=[["Dashboard",LayoutDashboard],["Machines",Cpu],["Preventive Maintenance",CalendarCheck],["Breakdown",AlertOctagon],["Spares",PackageSearch],["Reports",BarChart3],["Settings",Settings]];
const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)},go=n=>{setTab(n);setMobile(false)},show=k=>{setModal(k);setForm({...EMPTY[k]})},close=()=>{setModal(null);setForm(null)};
const filtered=k=>data[k].filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
const add=k=>{const p={machines:"MAC",pm:"PM",breakdowns:"BD",spares:"SPR"}[k];const id=`${p}-${String(data[k].length+1).padStart(4,"0")}`;setData({...data,[k]:[{id,...form},...data[k]]});close();notify("Record saved successfully.")};
const del=(k,id)=>{setData({...data,[k]:data[k].filter(r=>r.id!==id)});notify("Record deleted.")};
const status=(k,id,s)=>{setData({...data,[k]:data[k].map(r=>r.id===id?{...r,status:s}:r)});notify(`Status updated to ${s}.`)};
const login=e=>{e.preventDefault();if((email==="maintenance@techtarn.com"||email==="admin@techtarn.com")&&password==="Demo@123")setLogged(true);else notify("Use the demo credentials.")};
if(!logged)return <div className="login"><div className="loginCard"><div className="brand"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="loginTitle"><h1>Maintenance</h1><p>Machines • Preventive Maintenance • Breakdown • Spares</p></div><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Panel<select value={panel} onChange={e=>setPanel(e.target.value)}>{PANELS.map(x=><option key={x}>{x}</option>)}</select></label><button className="primary wide">Login <ChevronRight size={17}/></button></form><div className="demo">Demo: maintenance@techtarn.com / Demo@123</div></div></div>;

const counts={machines:data.machines.length,pm:data.pm.filter(x=>x.status!=="Completed").length,breakdowns:data.breakdowns.filter(x=>x.status!=="Resolved").length,spares:data.spares.filter(x=>x.status==="Low Stock").length};
const Table=({k,cols})=><div className="tableWrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}<th>Actions</th></tr></thead><tbody>{filtered(k).map(r=><tr key={r.id}>{cols.map(c=><td key={c[0]}>{["status","priority","criticality"].includes(c[0])?<span className={`badge ${String(r[c[0]]).toLowerCase().replaceAll(" ","-")}`}>{r[c[0]]}</span>:r[c[0]]}</td>)}<td className="actions">{k==="machines"&&r.status==="Maintenance Due"&&<button className="iconBtn" title="Mark running" onClick={()=>status(k,r.id,"Running")}><CheckCircle2 size={15}/></button>}{k==="pm"&&r.status!=="Completed"&&<button className="iconBtn" title="Complete PM" onClick={()=>status(k,r.id,"Completed")}><CheckCircle2 size={15}/></button>}{k==="breakdowns"&&r.status!=="Resolved"&&<button className="iconBtn" title="Resolve breakdown" onClick={()=>status(k,r.id,"Resolved")}><CheckCircle2 size={15}/></button>}{k==="spares"&&r.status==="Low Stock"&&<button className="iconBtn" title="Mark available" onClick={()=>status(k,r.id,"Available")}><CheckCircle2 size={15}/></button>}<button className="iconBtn danger" title="Delete" onClick={()=>del(k,r.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>;
const moduleView=(title,sub,k,cols,label)=><><div className="hero compact"><div><p className="eyebrow">MAINTENANCE</p><h1>{title}</h1><p>{sub}</p></div><button className="primary" onClick={()=>show(k)}><Plus size={17}/>{label}</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered(k).length} record(s)</span></div><div className="card"><Table k={k} cols={cols}/></div></>;

const content=()=>{
if(tab==="Dashboard")return <><div className="hero"><div><p className="eyebrow">MAINTENANCE CONTROL CENTER</p><h1>Maintenance Dashboard</h1><p>Manage machines, preventive maintenance, breakdowns and spare parts.</p></div><button className="primary" onClick={()=>show("breakdowns")}><Plus size={17}/> New Breakdown</button></div><div className="stats">{[["Machines",counts.machines,Cpu,"Machines"],["PM Open",counts.pm,CalendarCheck,"Preventive Maintenance"],["Breakdowns",counts.breakdowns,AlertOctagon,"Breakdown"],["Low Stock",counts.spares,PackageSearch,"Spares"]].map(([l,v,I,t])=><div className="stat" key={l}><div className="statIcon"><I size={18}/></div><div><span>{l}</span><strong>{v}</strong></div><button onClick={()=>go(t)}>Open</button></div>)}</div><div className="grid2"><div className="card"><div className="cardHead"><div><h3>Maintenance workflow</h3><p>Control assets from scheduled service through failure recovery.</p></div></div>{["Machine master","Preventive maintenance","Breakdown response","Spare parts control"].map((x,i)=><div className="workflow" key={x}><b>{i+1}</b><span>{x}</span><ChevronRight size={16}/></div>)}</div><div className="card"><div className="cardHead"><div><h3>Attention required</h3><p>Current maintenance exceptions.</p></div></div><div className="alert"><AlertTriangle size={17}/><span><b>{data.machines.filter(x=>x.status==="Maintenance Due").length}</b> machine(s) due for maintenance</span></div><div className="alert"><AlertTriangle size={17}/><span><b>{data.pm.filter(x=>x.status==="Overdue").length}</b> PM task(s) overdue</span></div><div className="alert"><Wrench size={17}/><span><b>{data.breakdowns.filter(x=>x.status!=="Resolved").length}</b> breakdown(s) open</span></div><div className="alert"><PackageSearch size={17}/><span><b>{counts.spares}</b> spare item(s) below minimum</span></div></div></div></div></>;
if(tab==="Machines")return moduleView("Machines","Maintain equipment master data, service history indicators and criticality.","machines",[["id","Machine ID"],["machine","Machine"],["code","Asset Code"],["line","Line"],["location","Location"],["criticality","Criticality"],["lastService","Last Service"],["status","Status"]],"Add Machine");
if(tab==="Preventive Maintenance")return moduleView("Preventive Maintenance","Schedule recurring maintenance tasks and track completion.","pm",[["id","PM ID"],["machine","Machine"],["asset","Asset"],["task","Task"],["frequency","Frequency"],["due","Due Date"],["technician","Technician"],["status","Status"]],"Add PM Task");
if(tab==="Breakdown")return moduleView("Breakdown","Log failures, assign technicians and track downtime to resolution.","breakdowns",[["id","Breakdown ID"],["machine","Machine"],["asset","Asset"],["issue","Issue"],["reported","Reported"],["priority","Priority"],["technician","Technician"],["downtime","Downtime"],["status","Status"]],"Log Breakdown");
if(tab==="Spares")return moduleView("Spares","Track maintenance spare quantities, minimum levels and locations.","spares",[["id","Spare ID"],["part","Part"],["sku","SKU"],["machine","Machine"],["qty","Qty"],["min","Min Qty"],["uom","UOM"],["location","Location"],["status","Status"]],"Add Spare");
if(tab==="Reports")return <><div className="hero compact"><div><p className="eyebrow">REPORTING</p><h1>Maintenance Reports</h1><p>Review assets, PM completion, breakdowns and spare availability.</p></div><button className="secondary" onClick={()=>notify("Maintenance report export prepared.")}><Download size={17}/> Export Report</button></div><div className="reportGrid">{[["Machines",counts.machines,"Registered assets"],["Open PM",counts.pm,"Tasks requiring completion"],["Breakdowns",counts.breakdowns,"Unresolved breakdowns"],["Low Stock",counts.spares,"Spares below minimum"]].map(([a,b,c])=><div className="reportCard" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small><div className="bar"><i style={{width:`${Math.min(100,Math.max(12,b*18))}%`}}/></div></div>)}</div></>;
return <div className="card settings"><div className="cardHead"><div><h2>Maintenance Settings</h2><p>Configure maintenance operating preferences for this prototype.</p></div></div><div className="formGrid"><label>Maintenance Store<input defaultValue="Maintenance Store"/></label><label>Default PM Frequency<select defaultValue="Monthly"><option>Weekly</option><option>Monthly</option><option>Quarterly</option><option>Annual</option></select></label><label>Breakdown Escalation<select defaultValue="Critical"><option>Critical</option><option>High</option><option>Medium</option></select></label><label>Default Technician Team<input defaultValue="Maintenance Team A"/></label></div><button className="primary" onClick={()=>notify("Settings saved successfully.")}><Save size={17}/> Save Settings</button></div>;
};

const fields={machines:["machine","code","line","location","criticality","lastService","status"],pm:["machine","asset","task","frequency","due","technician","status"],breakdowns:["machine","asset","issue","reported","priority","technician","downtime","status"],spares:["part","sku","machine","qty","min","uom","location","status"]};
const titles={machines:"Add Machine",pm:"Add Preventive Maintenance Task",breakdowns:"Log Breakdown",spares:"Add Spare"};
const opts={machines:["Running","Maintenance Due","Stopped"],pm:["Scheduled","In Progress","Overdue","Completed"],breakdowns:["Open","In Progress","Resolved"],spares:["Available","Low Stock","Blocked"]};
const Modal=({k})=><div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><div><h2>{titles[k]}</h2><p>Enter the maintenance data and save the record.</p></div><button className="iconBtn" onClick={close}><X size={18}/></button></div><div className="formGrid">{fields[k].map(f=><label key={f}>{f.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())}{f==="status"?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{opts[k].map(o=><option key={o}>{o}</option>)}</select>:f==="criticality"?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{["Low","Medium","High","Critical"].map(o=><option key={o}>{o}</option>)}</select>:f==="priority"?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{["Low","Medium","High","Critical"].map(o=><option key={o}>{o}</option>)}</select>:f==="frequency"?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{["Weekly","Monthly","Quarterly","Annual"].map(o=><option key={o}>{o}</option>)}</select>:<input required value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})} type={["lastService","due"].includes(f)?"date":"text"} placeholder={`Enter ${f}`}/>}</label>)}</div><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>add(k)}><Save size={17}/> Save Record</button></div></div></div>;

return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand side"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="panelTag">Maintenance</div><nav>{nav.map(([n,I])=><button key={n} className={tab===n?"nav active":"nav"} onClick={()=>go(n)}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideFoot"><span>Logged in as</span><b>{email}</b><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></aside><main><header><button className="menuBtn" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div><b>{tab}</b><span>Maintenance Panel</span></div><div className="headRight"><span>{BRAND.website}</span><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></header><section className="main">{content()}</section><HowWorks panel="Maintenance" module={tab}/></main><div className="tour"><div><b>Guide Tour · {tour+1}/{TOUR.length}</b><span>{TOUR[tour][0]} — {TOUR[tour][1]}</span></div><div className="tourBtns"><button disabled={tour===0} onClick={()=>setTour(Math.max(0,tour-1))}>Back</button><button className="primary" onClick={()=>{if(tour<TOUR.length-1){setTour(tour+1);go(TOUR[tour+1][0])}else notify("Guide tour completed.")}}>{tour===TOUR.length-1?"Finish":"Next"} <ChevronRight size={15}/></button></div></div>{modal&&<Modal k={modal}/>} {toast&&<div className="toast">{toast}</div>}</div>;
}
