import React,{useEffect,useState}from"react";
import HowWorks from "../how-works.jsx";
import{Archive,ArrowRight,Bell,CalendarDays,Check,ChevronDown,ChevronRight,ClipboardList,Clock3,Edit3,FileText,LayoutDashboard,LogOut,Menu,Package,Plus,Search,Settings,ShieldCheck,Trash2,Users,X,Factory,PlayCircle,PauseCircle}from"lucide-react";
import"./production.css";

const BRAND={phone:"+90 - 7453966757",email:"contact@techtarn.com",website:"www.techtarn.com"};
const PANELS=["Super Admin","Management / CEO","Sales & CRM","Purchase","Production","Quality / QA-QC","Raw Material / Inventory","Warehouse","Food Safety","Maintenance","Machine Operator","Finance & Accounts","HR & Payroll","Logistics / Distribution","Reports & Analytics"];
const plans=[
{id:"PP-1001",product:"Premium Tomato Puree 1kg",date:"2026-09-28",qty:1200,unit:"Cases",line:"Line A",status:"Scheduled"},
{id:"PP-1002",product:"Mango Pulp 850g",date:"2026-09-29",qty:800,unit:"Cases",line:"Line B",status:"Released"},
{id:"PP-1003",product:"Mixed Fruit Jam 500g",date:"2026-09-30",qty:1500,unit:"Cases",line:"Line A",status:"Draft"}];
const batches=[
{id:"BTH-3001",product:"Premium Tomato Puree 1kg",plan:"PP-1001",date:"2026-09-28",qty:600,status:"Running",yield:96},
{id:"BTH-3002",product:"Mango Pulp 850g",plan:"PP-1002",date:"2026-09-29",qty:400,status:"Completed",yield:98},
{id:"BTH-3003",product:"Mixed Fruit Jam 500g",plan:"PP-1003",date:"2026-09-30",qty:500,status:"Planned",yield:0}];
const recipes=[
{id:"REC-001",name:"Tomato Puree Standard",version:"v3.2",output:"1,000 kg",ingredients:"Tomato 1,050 kg; Salt 8 kg; Citric Acid 2 kg",status:"Active"},
{id:"REC-002",name:"Mango Pulp Standard",version:"v2.4",output:"1,000 kg",ingredients:"Mango 1,120 kg; Sugar 25 kg; Citric Acid 1.5 kg",status:"Active"},
{id:"REC-003",name:"Mixed Fruit Jam Standard",version:"v1.8",output:"1,000 kg",ingredients:"Fruit Mix 720 kg; Sugar 300 kg; Pectin 5 kg",status:"Draft"}];
const workOrders=[
{id:"WO-5001",batch:"BTH-3001",product:"Premium Tomato Puree 1kg",line:"Line A",start:"2026-09-28 08:00",end:"2026-09-28 16:00",qty:600,status:"Running"},
{id:"WO-5002",batch:"BTH-3002",product:"Mango Pulp 850g",line:"Line B",start:"2026-09-29 08:00",end:"2026-09-29 14:00",qty:400,status:"Completed"},
{id:"WO-5003",batch:"BTH-3003",product:"Mixed Fruit Jam 500g",line:"Line A",start:"2026-09-30 07:00",end:"2026-09-30 15:00",qty:500,status:"Planned"}];
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0});
const uid=p=>p+"-"+Math.random().toString(36).slice(2,8).toUpperCase();

export default function App(){
const[logged,setLogged]=useState(true),[panel,setPanel]=useState("Production"),[module,setModule]=useState("Dashboard"),[q,setQ]=useState(""),[side,setSide]=useState(false),[tour,setTour]=useState(true),[toast,setToast]=useState(""),[modal,setModal]=useState(null);
const[plans,setPlans]=useState(plans0()),[batches,setBatches]=useState(batches0()),[recipeData,setRecipeData]=useState(recipes0()),[orders,setOrders]=useState(wo0());
const[settings,setSettings]=useState({plant:"Main Food Processing Plant",shift:"General",uom:"Cases",alerts:true,session:"30 minutes"});
useEffect(()=>{if(toast){let t=setTimeout(()=>setToast(""),2300);return()=>clearTimeout(t)}},[toast]);
const notify=x=>setToast(x),log=(a,m)=>{};
const login=(e,p,panelName)=>{if((e==="production@techtarn.com"||e==="admin@techtarn.com")&&p==="Demo@123"){setPanel(panelName);setLogged(true);setModule("Dashboard");notify("Login successful.")}else notify("Invalid credentials. Password is Demo@123.")};
if(!logged)return <Login login={login}/>;
const nav=["Dashboard","Production Planning","Batch Processing","Recipes","Work Orders","Reports","Settings"];
const icons={Dashboard:<LayoutDashboard/>,"Production Planning":<CalendarDays/>,"Batch Processing":<Factory/>,"Recipes":<FileText/>,"Work Orders":<ClipboardList/>,Reports:<Archive/>,Settings:<Settings/>};
const create=()=>{let type={"Production Planning":"plan","Batch Processing":"batch","Recipes":"recipe","Work Orders":"wo"}[module];if(type)setModal(type)};
const next=()=>{let i=nav.indexOf(module);i<nav.length-1?setModule(nav[i+1]):setTour(false)};
return <div className="app">
<aside className={"sidebar "+(side?"open":"")}><div className="brand"><div className="mark">T</div><div><b>TechTarn</b><small>Food Processing ERP</small></div><button className="mobile icon" onClick={()=>setSide(false)}><X/></button></div><label>CURRENT PANEL</label><div className="panelBox">{panel}<ChevronDown/></div><label className="section">PRODUCTION</label><nav>{nav.map(n=><button className={"nav "+(module===n?"active":"")} onClick={()=>{setModule(n);setSide(false)}}>{icons[n]}<span>{n}</span></button>)}</nav><div className="foot"><ShieldCheck/> Secure ERP Workspace</div></aside>
<main className="main"><header className="top"><button className="mobile icon" onClick={()=>setSide(true)}><Menu/></button><div><small>{panel}</small><h1>{module}</h1></div><div className="actions"><div className="search"><Search/><input placeholder="Search current module..." value={q} onChange={e=>setQ(e.target.value)}/></div><button className="icon"><Bell/></button><div className="avatar">PD</div><button className="logout" onClick={()=>setLogged(false)}><LogOut/> Logout</button></div></header>
<section className="content">
{module==="Dashboard"&&<Dashboard plans={plans} batches={batches} recipes={recipeData} orders={orders} go={setModule}/>}
{module==="Production Planning"&&<Plans data={plans} setData={setPlans} q={q} open={create} notify={notify}/>}
{module==="Batch Processing"&&<Batches data={batches} setData={setBatches} q={q} open={create} notify={notify}/>}
{module==="Recipes"&&<Recipes data={recipeData} setData={setRecipeData} q={q} open={create} notify={notify}/>}
{module==="Work Orders"&&<WorkOrders data={orders} setData={setOrders} q={q} open={create} notify={notify}/>}
{module==="Reports"&&<Reports plans={plans} batches={batches} recipes={recipeData} orders={orders} notify={notify}/>}
{module==="Settings"&&<SettingsPage data={settings} setData={setSettings} save={()=>notify("Production settings saved.")}/>}
</section></main>
{tour&&<Tour module={module} next={next} close={()=>setTour(false)}/>}
{modal&&<Modal type={modal} close={()=>setModal(null)} plans={plans} batches={batches} recipes={recipeData} orders={orders} setPlans={setPlans} setBatches={setBatches} setRecipes={setRecipeData} setOrders={setOrders} notify={notify}/>}
{toast&&<div className="toast"><Check/>{toast}</div>}<HowWorks panel="Production" module={module}/></div>
}

function plans0(){return plans.map(x=>({...x}))}function batches0(){return batches.map(x=>({...x}))}function recipes0(){return recipes.map(x=>({...x}))}function wo0(){return workOrders.map(x=>({...x}))}
function Login({login}){const[e,setE]=useState("production@techtarn.com"),[p,setP]=useState("Demo@123"),[pn,setPn]=useState("Production");return <div className="login"><div className="loginCard"><div className="brand loginBrand"><div className="mark big">T</div><div><b>TechTarn</b><small>Food Processing ERP</small></div></div><span className="pill">ERP PROTOTYPE • PRODUCTION</span><h2>Welcome back</h2><p>Sign in to your authorized ERP panel.</p><form onSubmit={x=>{x.preventDefault();login(e,p,pn)}}><label>Email<input type="email" value={e} onChange={x=>setE(x.target.value)} required/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} required/></label><label>Login panel<select value={pn} onChange={x=>setPn(x.target.value)}>{PANELS.map(x=><option>{x}</option>)}</select></label><button className="primary full"><LogOut/> Sign in to {pn}</button></form><div className="demo"><b>Demo</b><span>production@techtarn.com</span><span>Password: Demo@123</span></div><footer>{BRAND.email} · {BRAND.phone} · {BRAND.website}</footer></div></div>}
function Intro({title,text,action}){return <div className="intro"><div><h2>{title}</h2><p>{text}</p></div>{action}</div>}function Action({children,onClick,secondary=false}){return <button className={secondary?"secondary":"primary"} onClick={onClick}>{children}</button>}function Head({title,text,action}){return <div className="head"><div><h3>{title}</h3><p>{text}</p></div>{action}</div>}function Table({title,text,children}){return <div className="card table"><Head title={title} text={text}/><div className="wrap">{children}</div></div>}
function Rows({edit,del}){return <div className="rows"><button onClick={edit}><Edit3/></button><button onClick={del}><Trash2/></button></div>}
function Dashboard({plans,batches,recipes,orders,go}){return <div className="page"><div className="hero"><div><span className="pill dark">PANEL 5 • PRODUCTION</span><h2>Production command center</h2><p>Plan production, execute batches, control recipes and manage work orders.</p></div><Action onClick={()=>go("Production Planning")}><Plus/> New Production Plan</Action></div><div className="stats">{[["Plans",plans.length,CalendarDays],["Active Batches",batches.filter(x=>x.status==="Running").length,Factory],["Active Recipes",recipes.filter(x=>x.status==="Active").length,FileText],["Open Work Orders",orders.filter(x=>x.status!=="Completed").length,ClipboardList]].map(([l,v,I])=><div className="stat"><I/><div><span>{l}</span><b>{v}</b></div></div>)}</div><div className="two"><div className="card"><Head title="Production workflow" text="Move from planning to execution."/><div className="tiles">{["Production Planning","Batch Processing","Recipes","Work Orders"].map((x,i)=><button onClick={()=>go(x)}><span>0{i+1}</span><b>{x}</b><ArrowRight/></button>)}</div></div><div className="card"><Head title="Shop-floor attention" text="Current production activity."/><div className="attention"><div><b>{plans.filter(x=>x.status==="Draft").length}</b><span>Draft plans</span></div><div><b>{batches.filter(x=>x.status==="Running").length}</b><span>Running batches</span></div><div><b>{orders.filter(x=>x.status==="Planned").length}</b><span>Planned work orders</span></div></div></div></div></div>}

function Plans({data,setData,q,open,notify}){let rows=data.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));let del=id=>{setData(data.filter(x=>x.id!==id));notify("Production plan deleted.")};let release=id=>{setData(data.map(x=>x.id===id?{...x,status:"Released"}:x));notify("Production plan released.")};return <div className="page"><Intro title="Production Planning" text="Schedule products, quantities, production dates and lines." action={<Action onClick={open}><Plus/> New Plan</Action>}/><Table title="Production plan register" text={rows.length+" plans"}><table><thead><tr><th>Plan</th><th>Product</th><th>Date / Line</th><th>Quantity</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.id}</b></td><td>{x.product}</td><td>{x.date}<small>{x.line}</small></td><td>{x.qty} {x.unit}</td><td><span className="status active">{x.status}</span></td><td><div className="rows"><button onClick={()=>release(x.id)}><PlayCircle/></button><button onClick={()=>del(x.id)}><Trash2/></button></div></td></tr>)}</tbody></table></Table></div>}
function Batches({data,setData,q,open,notify}){let rows=data.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));let del=id=>{setData(data.filter(x=>x.id!==id));notify("Batch deleted.")};let toggle=id=>{setData(data.map(x=>x.id===id?{...x,status:x.status==="Running"?"Planned":"Running"}:x));notify("Batch status updated.")};return <div className="page"><Intro title="Batch Processing" text="Track production batches, output quantities and yield." action={<Action onClick={open}><Plus/> Create Batch</Action>}/><Table title="Batch register" text={rows.length+" batches"}><table><thead><tr><th>Batch</th><th>Product / Plan</th><th>Date</th><th>Qty</th><th>Yield</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.id}</b></td><td>{x.product}<small>{x.plan}</small></td><td>{x.date}</td><td>{x.qty}</td><td>{x.yield?x.yield+"%":"—"}</td><td><span className="status active">{x.status}</span></td><td><div className="rows"><button onClick={()=>toggle(x.id)}>{x.status==="Running"?<PauseCircle/>:<PlayCircle/>}</button><button onClick={()=>del(x.id)}><Trash2/></button></div></td></tr>)}</tbody></table></Table></div>}
function Recipes({data,setData,q,open,notify}){let rows=data.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));let del=id=>{setData(data.filter(x=>x.id!==id));notify("Recipe deleted.")};return <div className="page"><Intro title="Recipes" text="Manage food formulas, versions, outputs and ingredients." action={<Action onClick={open}><Plus/> Add Recipe</Action>}/><Table title="Recipe master" text={rows.length+" recipes"}><table><thead><tr><th>Recipe</th><th>Version</th><th>Output</th><th>Ingredients</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.name}</b><small>{x.id}</small></td><td>{x.version}</td><td>{x.output}</td><td>{x.ingredients}</td><td><span className="status active">{x.status}</span></td><td><Rows edit={()=>notify("Recipe editor opened.")} del={()=>del(x.id)}/></td></tr>)}</tbody></table></Table></div>}
function WorkOrders({data,setData,q,open,notify}){let rows=data.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));let del=id=>{setData(data.filter(x=>x.id!==id));notify("Work order deleted.")};let complete=id=>{setData(data.map(x=>x.id===id?{...x,status:"Completed"}:x));notify("Work order completed.")};return <div className="page"><Intro title="Work Orders" text="Release, execute and complete production work orders." action={<Action onClick={open}><Plus/> New Work Order</Action>}/><Table title="Work order register" text={rows.length+" work orders"}><table><thead><tr><th>Work Order</th><th>Batch / Product</th><th>Line</th><th>Schedule</th><th>Qty</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.id}</b></td><td>{x.batch}<small>{x.product}</small></td><td>{x.line}</td><td>{x.start}<small>End {x.end}</small></td><td>{x.qty}</td><td><span className="status active">{x.status}</span></td><td><div className="rows"><button onClick={()=>complete(x.id)}><Check/></button><button onClick={()=>del(x.id)}><Trash2/></button></div></td></tr>)}</tbody></table></Table></div>}
function Reports({plans,batches,recipes,orders,notify}){return <div className="page"><Intro title="Production Reports" text="Management summaries for production execution." action={<Action secondary onClick={()=>notify("Production report export queued.")}><Archive/> Export</Action>}/><div className="reportGrid">{[["Planning",plans.length,CalendarDays],["Batches",batches.length,Factory],["Recipes",recipes.length,FileText],["Work Orders",orders.length,ClipboardList]].map(([a,b,I])=><div className="report card"><I/><span>{a}</span><b>{b}</b><small>Current demo data</small></div>)}</div></div>}
function SettingsPage({data,setData,save}){return <div className="page"><Intro title="Production Settings" text="Configure plant, shift, units and production alerts." action={<Action onClick={save}><Check/> Save Settings</Action>}/><div className="settings card"><h3>Production defaults</h3><div className="formGrid"><label>Plant<input value={data.plant} onChange={e=>setData({...data,plant:e.target.value})}/></label><label>Default shift<select value={data.shift} onChange={e=>setData({...data,shift:e.target.value})}><option>General</option><option>Morning</option><option>Evening</option><option>Night</option></select></label><label>Default UOM<select value={data.uom} onChange={e=>setData({...data,uom:e.target.value})}><option>Cases</option><option>Kg</option><option>Litres</option><option>Units</option></select></label><label>Session timeout<select value={data.session} onChange={e=>setData({...data,session:e.target.value})}><option>15 minutes</option><option>30 minutes</option><option>60 minutes</option></select></label><label className="check"><input type="checkbox" checked={data.alerts} onChange={e=>setData({...data,alerts:e.target.checked})}/> Enable production alerts</label></div></div></div>}
function Modal({type,close,plans,batches,recipes,orders,setPlans,setBatches,setRecipes,setOrders,notify}){let product="Premium Tomato Puree 1kg";let templates={plan:{product,date:"2026-10-01",qty:500,unit:"Cases",line:"Line A",status:"Draft"},batch:{product,plan:"PP-1001",date:"2026-10-01",qty:250,status:"Planned",yield:0},recipe:{name:"New Food Recipe",version:"v1.0",output:"1,000 kg",ingredients:"Ingredient A 500 kg; Ingredient B 500 kg",status:"Draft"},wo:{batch:"BTH-3001",product,line:"Line A",start:"2026-10-01 08:00",end:"2026-10-01 16:00",qty:250,status:"Planned"}};let[f,setF]=useState(templates[type]);let set=(k,v)=>setF({...f,[k]:v});let fields={plan:[["product","Product"],["date","Production date"],["qty","Quantity"],["unit","Unit"],["line","Production line"]],batch:[["product","Product"],["plan","Production plan"],["date","Batch date"],["qty","Quantity"]],recipe:[["name","Recipe name"],["version","Version"],["output","Output"],["ingredients","Ingredients"]],wo:[["batch","Batch"],["product","Product"],["line","Production line"],["start","Start"],["end","End"],["qty","Quantity"]]}[type];let title={plan:"New Production Plan",batch:"Create Batch",recipe:"Add Recipe",wo:"New Work Order"}[type];let save=e=>{e.preventDefault();if(type==="plan")setPlans([{...f,id:uid("PP")},...plans]);if(type==="batch")setBatches([{...f,id:uid("BTH")},...batches]);if(type==="recipe")setRecipes([{...f,id:uid("REC")},...recipes]);if(type==="wo")setOrders([{...f,id:uid("WO")},...orders]);notify("Record created successfully.");close()};return <div className="backdrop"><div className="modal"><div className="modalHead"><div><span className="pill">DATA ENTRY</span><h3>{title}</h3></div><button className="icon" onClick={close}><X/></button></div><form onSubmit={save}><div className="formGrid">{fields.map(([k,l])=><label>{l}<input required value={f[k]} onChange={e=>set(k,["qty"].includes(k)?Number(e.target.value):e.target.value)} type={k==="qty"?"number":k==="date"?"date":"text"}/></label>)}</div><div className="modalActions"><Action secondary onClick={close}>Cancel</Action><Action><Check/> Save Record</Action></div></form></div></div>}
function Tour({module,next,close}){return <div className="tour"><div className="tourTop"><span className="pill">GUIDE TOUR</span><button className="icon" onClick={close}><X/></button></div><h3>{module} module</h3><p>Create, search, update workflow status and delete demo records. Tables stay horizontally scrollable on narrow screens so production data is not clipped.</p><div className="tourFoot"><small>Step-by-step guide is active.</small><button className="primary small" onClick={next}>Next <ChevronRight/></button></div></div>}
