import React,{useEffect,useState} from "react";
import {Archive,ArrowRight,Bell,Check,ChevronDown,ChevronRight,ClipboardList,FileText,LayoutDashboard,LogOut,Menu,Package,Plus,Search,Settings,ShieldCheck,ShoppingCart,Trash2,Truck,Users,X,Edit3,Send,Database} from "lucide-react";
import "./purchase.css";
import HowWorks from "../how-works.jsx";

const BRAND={phone:"+90 - 7453966757",email:"contact@techtarn.com",website:"www.techtarn.com"};
const PANELS=["Super Admin","Management / CEO","Sales & CRM","Purchase","Production","Quality / QA-QC","Raw Material / Inventory","Warehouse","Food Safety","Maintenance","Machine Operator","Finance & Accounts","HR & Payroll","Logistics / Distribution","Reports & Analytics"];
const initialSuppliers=[
{id:"SUP-001",code:"V-1001",name:"AgroFresh Ingredients Pvt Ltd",contact:"Neha Kapoor",email:"neha@agrofresh.example",phone:"+91 98765 22001",city:"Delhi",terms:"30 Days",status:"Active"},
{id:"SUP-002",code:"V-1002",name:"Prime Packaging Solutions",contact:"Amit Verma",email:"amit@primepack.example",phone:"+91 98765 22002",city:"Noida",terms:"45 Days",status:"Active"},
{id:"SUP-003",code:"V-1003",name:"PureSpice Foods",contact:"Sanjay Rao",email:"sanjay@purespice.example",phone:"+91 98765 22003",city:"Jaipur",terms:"30 Days",status:"Active"}];
const initialRFQ=[
{id:"RFQ-1001",supplier:"AgroFresh Ingredients Pvt Ltd",date:"2026-09-22",due:"2026-09-29",items:8,value:185000,status:"Sent"},
{id:"RFQ-1002",supplier:"Prime Packaging Solutions",date:"2026-09-23",due:"2026-09-30",items:5,value:94000,status:"Draft"},
{id:"RFQ-1003",supplier:"PureSpice Foods",date:"2026-09-24",due:"2026-10-01",items:6,value:126500,status:"Quoted"}];
const initialPO=[
{id:"PO-2001",supplier:"AgroFresh Ingredients Pvt Ltd",date:"2026-09-23",delivery:"2026-10-05",items:10,total:284000,status:"Approved"},
{id:"PO-2002",supplier:"Prime Packaging Solutions",date:"2026-09-24",delivery:"2026-10-08",items:7,total:157500,status:"Sent"},
{id:"PO-2003",supplier:"PureSpice Foods",date:"2026-09-25",delivery:"2026-10-10",items:5,total:113600,status:"Draft"}];
const initialGRN=[
{id:"GRN-3001",po:"PO-1998",supplier:"AgroFresh Ingredients Pvt Ltd",date:"2026-09-24",items:9,qty:240,status:"Accepted"},
{id:"GRN-3002",po:"PO-2001",supplier:"AgroFresh Ingredients Pvt Ltd",date:"2026-09-25",items:10,qty:180,status:"Pending QC"},
{id:"GRN-3003",po:"PO-1995",supplier:"Prime Packaging Solutions",date:"2026-09-25",items:6,qty:120,status:"Accepted"}];
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0});
const uid=p=>p+"-"+Math.random().toString(36).slice(2,8).toUpperCase();

export default function App(){
 const [logged,setLogged]=useState(true),[panel,setPanel]=useState("Purchase"),[module,setModule]=useState("Dashboard"),[q,setQ]=useState(""),[side,setSide]=useState(false),[tour,setTour]=useState(true),[toast,setToast]=useState(""),[modal,setModal]=useState(null);
 const [suppliers,setSuppliers]=useState(initialSuppliers),[rfq,setRfq]=useState(initialRFQ),[po,setPo]=useState(initialPO),[grn,setGrn]=useState(initialGRN);
 const [settings,setSettings]=useState({currency:"INR",approval:"2-step",alerts:true,session:"30 minutes"});
 const [audit,setAudit]=useState([{id:"AUD-P1",time:"25 Sep 2026 10:45",user:"Purchase Demo",action:"Login",module:"Authentication"},{id:"AUD-P2",time:"25 Sep 2026 10:40",user:"Purchase Demo",action:"Viewed",module:"Purchase Orders"}]);
 useEffect(()=>{if(toast){let t=setTimeout(()=>setToast(""),2300);return()=>clearTimeout(t)}},[toast]);
 const notify=x=>setToast(x),log=(a,m)=>setAudit(x=>[{id:uid("AUD"),time:new Date().toLocaleString("en-GB"),user:"Purchase Demo",action:a,module:m},...x]);
 const login=(email,pwd,p)=>{if((email==="purchase@techtarn.com"||email==="admin@techtarn.com")&&pwd==="Demo@123"){setPanel(p);setLogged(true);setModule("Dashboard");log("Login","Authentication");notify("Login successful.")}else notify("Invalid credentials. Password is Demo@123.")};
 if(!logged)return <Login login={login}/>;
 const nav=["Dashboard","Suppliers","RFQ","Purchase Orders","GRN","Reports","Settings"];
 const icons={Dashboard:<LayoutDashboard/>,Suppliers:<Users/>,RFQ:<FileText/>,"Purchase Orders":<ShoppingCart/>,GRN:<Package/>,Reports:<Archive/>,Settings:<Settings/>};
 const create=()=>setModal({Dashboard:null,Suppliers:"supplier",RFQ:"rfq","Purchase Orders":"po",GRN:"grn"}[module]);
 const next=()=>{let i=nav.indexOf(module);i<nav.length-1?setModule(nav[i+1]):setTour(false)};
 return <div className="app">
 <aside className={"sidebar "+(side?"open":"")}><div className="brand"><div className="mark">T</div><div><b>TechTarn</b><small>Food Processing ERP</small></div><button className="mobile icon" onClick={()=>setSide(false)}><X/></button></div><label>CURRENT PANEL</label><div className="panelBox">{panel}<ChevronDown/></div><label className="section">PURCHASE</label><nav>{nav.map(n=><button className={"nav "+(module===n?"active":"")} onClick={()=>{setModule(n);setSide(false)}}>{icons[n]}<span>{n}</span></button>)}</nav><div className="foot"><ShieldCheck/> Secure ERP Workspace</div></aside>
 <main className="main"><header className="top"><button className="mobile icon" onClick={()=>setSide(true)}><Menu/></button><div><small>{panel}</small><h1>{module}</h1></div><div className="actions"><div className="search"><Search/><input placeholder="Search current module..." value={q} onChange={e=>setQ(e.target.value)}/></div><button className="icon"><Bell/></button><div className="avatar">PD</div><button className="logout" onClick={()=>setLogged(false)}><LogOut/> Logout</button></div></header>
 <section className="content">
 {module==="Dashboard"&&<Dashboard suppliers={suppliers} rfq={rfq} po={po} grn={grn} go={setModule}/>}
 {module==="Suppliers"&&<Suppliers data={suppliers} setData={setSuppliers} q={q} open={create} notify={notify} log={log}/>}
 {module==="RFQ"&&<RFQ data={rfq} setData={setRfq} q={q} open={create} notify={notify} log={log}/>}
 {module==="Purchase Orders"&&<PO data={po} setData={setPo} q={q} open={create} notify={notify} log={log}/>}
 {module==="GRN"&&<GRN data={grn} setData={setGrn} q={q} open={create} notify={notify} log={log}/>}
 {module==="Reports"&&<Reports suppliers={suppliers} rfq={rfq} po={po} grn={grn} notify={notify}/>}
 {module==="Settings"&&<SettingsPage data={settings} setData={setSettings} save={()=>{log("Updated","Settings");notify("Purchase settings saved.")}}/>}
 </section></main>
 {tour&&<Tour module={module} next={next} close={()=>setTour(false)}/>}
 {modal&&<Modal type={modal} close={()=>setModal(null)} suppliers={suppliers} rfq={rfq} po={po} setSuppliers={setSuppliers} setRfq={setRfq} setPo={setPo} setGrn={setGrn} grn={grn} log={log} notify={notify}/>}
 {toast&&<div className="toast"><Check/>{toast}</div>}
 <HowWorks panel="Purchase" module={module}/></div>
}

function Login({login}){const [e,setE]=useState("purchase@techtarn.com"),[p,setP]=useState("Demo@123"),[panel,setPanel]=useState("Purchase");return <div className="login"><div className="loginCard"><div className="brand loginBrand"><div className="mark big">T</div><div><b>TechTarn</b><small>Food Processing ERP</small></div></div><span className="pill">ERP PROTOTYPE • PURCHASE</span><h2>Welcome back</h2><p>Sign in to your authorized ERP panel.</p><form onSubmit={x=>{x.preventDefault();login(e,p,panel)}}><label>Email<input type="email" value={e} onChange={x=>setE(x.target.value)} required/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} required/></label><label>Login panel<select value={panel} onChange={x=>setPanel(x.target.value)}>{PANELS.map(x=><option>{x}</option>)}</select></label><button className="primary full"><LogOut/> Sign in to {panel}</button></form><div className="demo"><b>Demo</b><span>purchase@techtarn.com</span><span>Password: Demo@123</span></div><footer>{BRAND.email} · {BRAND.phone} · {BRAND.website}</footer></div></div>}

function Intro({title,text,action}){return <div className="intro"><div><h2>{title}</h2><p>{text}</p></div>{action}</div>}
function Action({children,onClick,secondary=false}){return <button className={secondary?"secondary":"primary"} onClick={onClick}>{children}</button>}
function Head({title,text,action}){return <div className="head"><div><h3>{title}</h3><p>{text}</p></div>{action}</div>}
function Table({title,text,children,action}){return <div className="card table"><Head title={title} text={text} action={action}/><div className="wrap">{children}</div></div>}
function RowActions({edit,del}){return <div className="rows"><button onClick={edit}><Edit3/></button><button onClick={del}><Trash2/></button></div>}
function Dashboard({suppliers,rfq,po,grn,go}){let val=po.reduce((s,x)=>s+x.total,0);return <div className="page"><div className="hero"><div><span className="pill dark">PANEL 4 • PURCHASE</span><h2>Purchase command center</h2><p>Supplier, RFQ, purchase order and goods receipt control.</p></div><Action onClick={()=>go("Purchase Orders")}><Plus/> New Purchase Order</Action></div><div className="stats">{[["Suppliers",suppliers.length,Users],["RFQ",rfq.length,FileText],["PO Value",money(val),ShoppingCart],["GRN Pending QC",grn.filter(x=>x.status==="Pending QC").length,Package]].map(([l,v,I])=><div className="stat"><I/><div><span>{l}</span><b>{v}</b></div></div>)}</div><div className="two"><div className="card"><Head title="Purchase workflow" text="Manage the procurement lifecycle."/><div className="tiles">{["Suppliers","RFQ","Purchase Orders","GRN"].map((x,i)=><button onClick={()=>go(x)}><span>0{i+1}</span><b>{x}</b><ArrowRight/></button>)}</div></div><div className="card"><Head title="Attention" text="Current purchase activity."/><div className="attention"><div><b>{rfq.filter(x=>x.status==="Draft").length}</b><span>Draft RFQs</span></div><div><b>{po.filter(x=>x.status==="Draft").length}</b><span>Draft purchase orders</span></div><div><b>{grn.filter(x=>x.status==="Pending QC").length}</b><span>GRNs pending QC</span></div></div></div></div></div>}

function Suppliers({data,setData,q,open,notify,log}){let rows=data.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));let del=id=>{setData(data.filter(x=>x.id!==id));log("Deleted","Suppliers");notify("Supplier deleted.")};return <div className="page"><Intro title="Suppliers" text="Manage supplier master records, contacts and payment terms." action={<Action onClick={open}><Plus/> Add Supplier</Action>}/><Table title="Supplier directory" text={rows.length+" supplier records"}><table><thead><tr><th>Supplier</th><th>Contact</th><th>Location</th><th>Payment terms</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.name}</b><small>{x.code} · {x.email}</small></td><td>{x.contact}<small>{x.phone}</small></td><td>{x.city}</td><td>{x.terms}</td><td><span className="status active">{x.status}</span></td><td><RowActions edit={()=>notify("Supplier editor opened.")} del={()=>del(x.id)}/></td></tr>)}</tbody></table></Table></div>}

function RFQ({data,setData,q,open,notify,log}){let rows=data.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));let del=id=>{setData(data.filter(x=>x.id!==id));log("Deleted","RFQ");notify("RFQ deleted.")};let send=id=>{setData(data.map(x=>x.id===id?{...x,status:"Sent"}:x));log("Updated","RFQ");notify("RFQ sent to supplier.")};return <div className="page"><Intro title="RFQ" text="Request supplier quotations and track responses." action={<Action onClick={open}><Plus/> New RFQ</Action>}/><Table title="RFQ register" text="RFQ dates, supplier response and estimated value."><table><thead><tr><th>RFQ</th><th>Supplier</th><th>Date / Due</th><th>Items</th><th>Value</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.id}</b></td><td>{x.supplier}</td><td>{x.date}<small>Due {x.due}</small></td><td>{x.items}</td><td>{money(x.value)}</td><td><span className="status neutral">{x.status}</span></td><td><div className="rows"><button onClick={()=>send(x.id)}><Send/></button><button onClick={()=>del(x.id)}><Trash2/></button></div></td></tr>)}</tbody></table></Table></div>}

function PO({data,setData,q,open,notify,log}){let rows=data.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));let del=id=>{setData(data.filter(x=>x.id!==id));log("Deleted","Purchase Orders");notify("Purchase order deleted.")};let next=id=>{let seq=["Draft","Sent","Approved","Closed"],x=data.find(a=>a.id===id),i=seq.indexOf(x.status);setData(data.map(a=>a.id===id?{...a,status:seq[Math.min(i+1,3)]}:a));log("Updated","Purchase Orders");notify("Purchase order status updated.")};return <div className="page"><Intro title="Purchase Orders" text="Create and track supplier purchase orders." action={<Action onClick={open}><Plus/> New Purchase Order</Action>}/><Table title="Purchase order register" text="Supplier commitments, delivery dates and values."><table><thead><tr><th>PO</th><th>Supplier</th><th>Order / Delivery</th><th>Items</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.id}</b></td><td>{x.supplier}</td><td>{x.date}<small>Delivery {x.delivery}</small></td><td>{x.items}</td><td>{money(x.total)}</td><td><span className="status active">{x.status}</span></td><td><div className="rows"><button onClick={()=>next(x.id)}><Check/></button><button onClick={()=>del(x.id)}><Trash2/></button></div></td></tr>)}</tbody></table></Table></div>}

function GRN({data,setData,q,open,notify,log}){let rows=data.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));let del=id=>{setData(data.filter(x=>x.id!==id));log("Deleted","GRN");notify("GRN deleted.")};let accept=id=>{setData(data.map(x=>x.id===id?{...x,status:"Accepted"}:x));log("Updated","GRN");notify("GRN accepted.")};return <div className="page"><Intro title="GRN" text="Record goods received against purchase orders and QC status." action={<Action onClick={open}><Plus/> Create GRN</Action>}/><Table title="Goods receipt register" text="Inbound quantity and acceptance status."><table><thead><tr><th>GRN</th><th>PO / Supplier</th><th>Date</th><th>Items</th><th>Quantity</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.id}</b></td><td>{x.po}<small>{x.supplier}</small></td><td>{x.date}</td><td>{x.items}</td><td>{x.qty}</td><td><span className={"status "+(x.status==="Accepted"?"active":"neutral")}>{x.status}</span></td><td><div className="rows"><button onClick={()=>accept(x.id)}><Check/></button><button onClick={()=>del(x.id)}><Trash2/></button></div></td></tr>)}</tbody></table></Table></div>}

function Reports({suppliers,rfq,po,grn,notify}){return <div className="page"><Intro title="Purchase Reports" text="Management summaries for procurement activity." action={<Action secondary onClick={()=>notify("Purchase report export queued.")}><Archive/> Export</Action>}/><div className="reportGrid">{[["Supplier report",suppliers.length,Users],["RFQ report",rfq.length,FileText],["PO value",money(po.reduce((s,x)=>s+x.total,0)),ShoppingCart],["GRN report",grn.length,Package]].map(([a,b,I])=><div className="report card"><I/><span>{a}</span><b>{b}</b><small>Current demo data</small></div>)}</div></div>}
function SettingsPage({data,setData,save}){return <div className="page"><Intro title="Purchase Settings" text="Configure procurement defaults and approval workflow." action={<Action onClick={save}><Check/> Save Settings</Action>}/><div className="settings card"><h3>Procurement defaults</h3><div className="formGrid"><label>Currency<select value={data.currency} onChange={e=>setData({...data,currency:e.target.value})}><option>INR</option><option>USD</option><option>EUR</option></select></label><label>PO approval<input value={data.approval} onChange={e=>setData({...data,approval:e.target.value})}/></label><label>Session timeout<select value={data.session} onChange={e=>setData({...data,session:e.target.value})}><option>15 minutes</option><option>30 minutes</option><option>60 minutes</option></select></label><label className="check"><input type="checkbox" checked={data.alerts} onChange={e=>setData({...data,alerts:e.target.checked})}/> Enable purchase alerts</label></div></div></div>}

function Modal({type,close,suppliers,rfq,po,grn,setSuppliers,setRfq,setPo,setGrn,log,notify}){let s=suppliers[0]?.name||"AgroFresh Ingredients Pvt Ltd";let p=po[0]?.id||"PO-2001";let templates={supplier:{name:"New Supplier",code:"V-"+Math.floor(1000+Math.random()*8999),contact:"Contact Person",email:"supplier@example.com",phone:"+91 98765 00000",city:"Delhi",terms:"30 Days",status:"Active"},rfq:{supplier:s,date:"2026-09-25",due:"2026-10-02",items:5,value:100000,status:"Draft"},po:{supplier:s,date:"2026-09-25",delivery:"2026-10-10",items:5,total:100000,status:"Draft"},grn:{po:p,supplier:s,date:"2026-09-25",items:5,qty:100,status:"Pending QC"}};let [f,setF]=useState(templates[type]);let set=(k,v)=>setF({...f,[k]:v});let fields={supplier:[["name","Supplier name"],["code","Supplier code"],["contact","Contact person"],["email","Email"],["phone","Phone"],["city","City"],["terms","Payment terms"]],rfq:[["supplier","Supplier"],["date","RFQ date"],["due","Response due"],["items","Items"],["value","Estimated value"]],po:[["supplier","Supplier"],["date","PO date"],["delivery","Delivery date"],["items","Items"],["total","Total value"]],grn:[["po","Purchase order"],["supplier","Supplier"],["date","Receipt date"],["items","Items"],["qty","Quantity"]]}[type];let save=e=>{e.preventDefault();let id=type==="supplier"?"SUP":type==="rfq"?"RFQ":type==="po"?"PO":"GRN";if(type==="supplier")setSuppliers([{...f,id:uid(id)},...suppliers]);if(type==="rfq")setRfq([{...f,id:uid(id)},...rfq]);if(type==="po")setPo([{...f,id:uid(id)},...po]);if(type==="grn")setGrn([{...f,id:uid(id)},...grn]);log("Created",type==="po"?"Purchase Orders":type.toUpperCase());notify("Record created successfully.");close()};let title={supplier:"Add Supplier",rfq:"New RFQ",po:"New Purchase Order",grn:"Create GRN"}[type];return <div className="backdrop"><div className="modal"><div className="modalHead"><div><span className="pill">DATA ENTRY</span><h3>{title}</h3></div><button className="icon" onClick={close}><X/></button></div><form onSubmit={save}><div className="formGrid">{fields.map(([k,l])=><label>{l}<input required type={["items","value","total","qty"].includes(k)?"number":k.includes("date")||k==="due"||k==="delivery"?"date":k==="email"?"email":"text"} value={f[k]} onChange={e=>set(k,["items","value","total","qty"].includes(k)?Number(e.target.value):e.target.value)}/></label>)}</div><div className="modalActions"><Action secondary onClick={close}>Cancel</Action><Action><Check/> Save Record</Action></div></form></div></div>}

function Tour({module,next,close}){return <div className="tour"><div className="tourTop"><span className="pill">GUIDE TOUR</span><button className="icon" onClick={close}><X/></button></div><h3>{module} module</h3><p>Create, search, update workflow status and delete demo records. Tables remain horizontally scrollable on narrow screens so no data is clipped.</p><div className="tourFoot"><small>Step-by-step guide is active.</small><button className="primary small" onClick={next}>Next <ChevronRight/></button></div></div>}
