import React,{useMemo,useState} from "react";
import {LayoutDashboard,ClipboardCheck,Beaker,FileCheck2,ShieldAlert,Scale,BarChart3,Settings,Menu,LogOut,Plus,Search,Trash2,Play,CheckCircle2,Save,X,ChevronRight,Download,Edit3,AlertTriangle} from "lucide-react";
import "./quality.css";
import HowWorks from "../how-works.jsx";

const BRAND={name:"TechTarn",website:"www.techtarn.com",phone:"+90 - 7453966757",email:"contact@techtarn.com"};
const PANELS=["Super Admin","Management / CEO","Sales & CRM","Purchase","Production","Quality / QA-QC","Raw Material / Inventory","Warehouse","Food Safety","Maintenance","Machine Operator","Finance & Accounts","HR & Payroll","Logistics / Distribution","Reports & Analytics"];
const DEMO={
 tests:[
  {id:"QCT-1001",sample:"Tomato Puree — Batch BTH-3001",parameter:"pH",spec:"3.8–4.2",result:"4.0",unit:"pH",status:"Pass",date:"2026-09-28"},
  {id:"QCT-1002",sample:"Mango Pulp — Batch BTH-3002",parameter:"Brix",spec:"14–16",result:"15.2",unit:"°Bx",status:"Pass",date:"2026-09-29"},
  {id:"QCT-1003",sample:"Mixed Fruit Jam — Batch BTH-3003",parameter:"Viscosity",spec:"2,500–3,500",result:"3,780",unit:"cP",status:"Fail",date:"2026-09-30"}
 ],
 samples:[
  {id:"SMP-2001",source:"Production",ref:"BTH-3001",product:"Tomato Puree",qty:"250",unit:"ml",collectedBy:"QC Analyst",status:"Collected"},
  {id:"SMP-2002",source:"Incoming",ref:"RM-4501",product:"Fresh Mango",qty:"500",unit:"g",collectedBy:"QC Analyst",status:"Under Test"},
  {id:"SMP-2003",source:"Production",ref:"BTH-3003",product:"Mixed Fruit Jam",qty:"250",unit:"ml",collectedBy:"QC Analyst",status:"Pending"}
 ],
 specs:[
  {id:"SPEC-001",product:"Tomato Puree 1kg",parameter:"pH",target:"3.8–4.2",method:"pH Meter",version:"3.2",status:"Active"},
  {id:"SPEC-002",product:"Mango Pulp 850g",parameter:"Brix",target:"14–16 °Bx",method:"Refractometer",version:"2.4",status:"Active"},
  {id:"SPEC-003",product:"Mixed Fruit Jam 500g",parameter:"Viscosity",target:"2,500–3,500 cP",method:"Brookfield",version:"1.8",status:"Draft"}
 ],
 capas:[
  {id:"CAPA-001",issue:"Jam viscosity above specification",source:"QC Test QCT-1003",owner:"QA Manager",due:"2026-10-05",priority:"High",status:"Open"},
  {id:"CAPA-002",issue:"Incoming mango sample delayed",source:"Sampling SMP-2002",owner:"QC Supervisor",due:"2026-10-02",priority:"Medium",status:"In Progress"},
  {id:"CAPA-003",issue:"pH meter calibration reminder",source:"Audit",owner:"QC Analyst",due:"2026-10-10",priority:"Low",status:"Closed"}
 ],
 compliance:[
  {id:"CMP-001",requirement:"GMP — Batch release records",owner:"QA Manager",next:"2026-10-15",status:"Compliant"},
  {id:"CMP-002",requirement:"HACCP — CCP monitoring evidence",owner:"Food Safety Lead",next:"2026-10-20",status:"Review Due"},
  {id:"CMP-003",requirement:"Internal QC documentation audit",owner:"QA Supervisor",next:"2026-10-05",status:"Open"}
 ]
};

const empty={tests:{sample:"",parameter:"",spec:"",result:"",unit:"",date:""},samples:{source:"",ref:"",product:"",qty:"",unit:"",collectedBy:"",status:"Pending"},specs:{product:"",parameter:"",target:"",method:"",version:"1.0",status:"Draft"},capas:{issue:"",source:"",owner:"",due:"",priority:"Medium",status:"Open"},compliance:{requirement:"",owner:"",next:"",status:"Open"}};
const tour=[["Dashboard","Review QC health, open CAPA and compliance alerts."],["QC Tests","Record laboratory results and compare against specifications."],["Sampling","Create and track samples from incoming and production sources."],["Specifications","Maintain product quality limits, methods and versions."],["CAPA","Assign corrective and preventive actions and track closure."],["Compliance","Track quality requirements, owners and review dates."],["Reports","Export quality summaries for management review."],["Settings","Save QA/QC operating preferences."]];

export default function App(){
 const [logged,setLogged]=useState(true),[email,setEmail]=useState("quality@techtarn.com"),[password,setPassword]=useState("Demo@123"),[panel,setPanel]=useState("Quality / QA-QC");
 const [tab,setTab]=useState("Dashboard"),[mobile,setMobile]=useState(false),[query,setQuery]=useState(""),[data,setData]=useState(DEMO),[modal,setModal]=useState(null),[form,setForm]=useState(null),[tourStep,setTourStep]=useState(0),[toast,setToast]=useState("");
 const nav=[["Dashboard",LayoutDashboard],["QC Tests",Beaker],["Sampling",ClipboardCheck],["Specifications",FileCheck2],["CAPA",ShieldAlert],["Compliance",Scale],["Reports",BarChart3],["Settings",Settings]];
 const show=(m)=>{setModal(m);setForm({...empty[m]})};
 const close=()=>{setModal(null);setForm(null)};
 const notify=(m)=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 const filtered=(key)=>data[key].filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));
 const add=(key)=>{
   const prefix={tests:"QCT",samples:"SMP",specs:"SPEC",capas:"CAPA",compliance:"CMP"}[key];
   const next=`${prefix}-${String(data[key].length+1).padStart(4,"0")}`;
   const row={id:next,...form};
   setData({...data,[key]:[row,...data[key]]}); close(); notify("Record saved successfully.");
 };
 const del=(key,id)=>{setData({...data,[key]:data[key].filter(x=>x.id!==id)});notify("Record deleted.");};
 const updateStatus=(key,id,status)=>{setData({...data,[key]:data[key].map(x=>x.id===id?{...x,status}:x)});notify(`Status updated to ${status}.`);};
 const login=(e)=>{e.preventDefault(); if((email==="quality@techtarn.com"||email==="admin@techtarn.com")&&password==="Demo@123"){setLogged(true)}else notify("Use the demo credentials.");};
 const go=(name)=>{setTab(name);setMobile(false)};
 if(!logged)return <div className="login"><div className="loginCard"><div className="brand"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="loginTitle"><h1>Quality / QA-QC</h1><p>QC Tests • Sampling • Specifications • CAPA • Compliance</p></div><form onSubmit={login}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label><label>Panel<select value={panel} onChange={e=>setPanel(e.target.value)}>{PANELS.map(p=><option key={p}>{p}</option>)}</select></label><button className="primary wide">Login <ChevronRight size={17}/></button></form><div className="demo">Demo: quality@techtarn.com / Demo@123</div></div></div>;

 const counts={tests:data.tests.length,samples:data.samples.length,specs:data.specs.length,capas:data.capas.filter(x=>x.status!=="Closed").length,compliance:data.compliance.filter(x=>x.status!=="Compliant").length};
 const Table=({keyName,columns,actions=true})=><div className="tableWrap"><table><thead><tr>{columns.map(c=><th key={c.k}>{c.l}</th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{filtered(keyName).map(r=><tr key={r.id}>{columns.map(c=><td key={c.k}>{c.k==="status"?<span className={`badge ${String(r[c.k]).toLowerCase().replaceAll(" ","-")}`}>{r[c.k]}</span>:r[c.k]}</td>)}{actions&&<td className="actions">{(keyName==="tests"||keyName==="samples")&&<button className="iconBtn" title="Edit / status" onClick={()=>updateStatus(keyName,r.id,keyName==="tests"?(r.status==="Pass"?"Review":"Pass"):(r.status==="Pending"?"Under Test":"Collected"))}><Edit3 size={15}/></button>} {keyName==="capas"&&r.status!=="Closed"&&<button className="iconBtn" title="Close CAPA" onClick={()=>updateStatus(keyName,r.id,"Closed")}><CheckCircle2 size={15}/></button>} {keyName==="compliance"&&r.status!=="Compliant"&&<button className="iconBtn" title="Mark compliant" onClick={()=>updateStatus(keyName,r.id,"Compliant")}><CheckCircle2 size={15}/></button>}<button className="iconBtn danger" title="Delete" onClick={()=>del(keyName,r.id)}><Trash2 size={15}/></button></td>}</tr>)}</tbody></table></div>;

 const content=()=>{
  if(tab==="Dashboard")return <><div className="hero"><div><p className="eyebrow">QUALITY CONTROL CENTER</p><h1>QA / QC Dashboard</h1><p>Control testing, sampling, specifications, CAPA and compliance from one workspace.</p></div><button className="primary" onClick={()=>show("tests")}><Plus size={17}/> New QC Test</button></div><div className="stats">{[["QC Tests",counts.tests,Beaker,"QC Tests"],["Samples",counts.samples,ClipboardCheck,"Sampling"],["Open CAPA",counts.capas,ShieldAlert,"CAPA"],["Compliance Review",counts.compliance,Scale,"Compliance"]].map(([l,v,I,t])=><div className="stat" key={l}><div className="statIcon"><I size={18}/></div><div><span>{l}</span><strong>{v}</strong></div><button onClick={()=>go(t)}>Open</button></div>)}</div><div className="grid2"><div className="card"><div className="cardHead"><div><h3>Quality workflow</h3><p>Follow the standard QA/QC cycle.</p></div></div>{["Sample collection","QC test execution","Specification check","CAPA / disposition","Compliance evidence"].map((x,i)=><div className="workflow" key={x}><b>{i+1}</b><span>{x}</span><ChevronRight size={16}/></div>)}</div><div className="card"><div className="cardHead"><div><h3>Attention required</h3><p>Items needing review.</p></div></div><div className="alert"><AlertTriangle size={17}/><span><b>{counts.capas}</b> CAPA item(s) not closed</span></div><div className="alert"><AlertTriangle size={17}/><span><b>{counts.compliance}</b> compliance item(s) need attention</span></div><div className="alert"><CheckCircle2 size={17}/><span>Latest QC data is available for review</span></div></div></div></>;
  if(tab==="QC Tests")return <Module title="QC Tests" sub="Record test results and compare against approved specifications." keyName="tests" cols={[["id","Test ID"],["sample","Sample"],["parameter","Parameter"],["spec","Specification"],["result","Result"],["unit","Unit"],["status","Status"],["date","Date"]]} />;
  if(tab==="Sampling")return <Module title="Sampling" sub="Create and track incoming and production samples." keyName="samples" cols={[["id","Sample ID"],["source","Source"],["ref","Reference"],["product","Product"],["qty","Qty"],["unit","Unit"],["collectedBy","Collected By"],["status","Status"]]} />;
  if(tab==="Specifications")return <Module title="Specifications" sub="Maintain product limits, test methods and controlled versions." keyName="specs" cols={[["id","Spec ID"],["product","Product"],["parameter","Parameter"],["target","Target"],["method","Method"],["version","Version"],["status","Status"]]} />;
  if(tab==="CAPA")return <Module title="CAPA" sub="Track corrective and preventive actions to closure." keyName="capas" cols={[["id","CAPA ID"],["issue","Issue"],["source","Source"],["owner","Owner"],["due","Due Date"],["priority","Priority"],["status","Status"]]} />;
  if(tab==="Compliance")return <Module title="Compliance" sub="Track quality requirements, ownership and review dates." keyName="compliance" cols={[["id","ID"],["requirement","Requirement"],["owner","Owner"],["next","Next Review"],["status","Status"]]} />;
  if(tab==="Reports")return <><div className="hero compact"><div><p className="eyebrow">REPORTING</p><h1>Quality Reports</h1><p>Review test, sampling, CAPA and compliance summaries.</p></div><button className="secondary" onClick={()=>notify("Report export prepared for download.")}><Download size={17}/> Export Report</button></div><div className="reportGrid">{[["QC Test Summary",counts.tests,"Tests recorded"],["Sampling Status",counts.samples,"Samples tracked"],["CAPA Open",counts.capas,"Actions requiring closure"],["Compliance Attention",counts.compliance,"Items to review"]].map(([a,b,c])=><div className="reportCard" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small><div className="bar"><i style={{width:`${Math.min(100,Math.max(12,b*18))}%`}}/></div></div>)}</div></>;
  return <div className="card settings"><div className="cardHead"><div><h2>QA/QC Settings</h2><p>Configure quality operating preferences for this prototype.</p></div></div><div className="formGrid"><label>Default QC site<input defaultValue="TechTarn Food Processing — Main Plant"/></label><label>Result review SLA<select defaultValue="24 hours"><option>12 hours</option><option>24 hours</option><option>48 hours</option></select></label><label>CAPA escalation<select defaultValue="48 hours"><option>24 hours</option><option>48 hours</option><option>72 hours</option></select></label><label>Compliance owner<input defaultValue="QA Manager"/></label></div><button className="primary" onClick={()=>notify("Settings saved successfully.")}><Save size={17}/> Save Settings</button></div>;
 function Module({title,sub,keyName,cols}){return <><div className="hero compact"><div><p className="eyebrow">QUALITY / QA-QC</p><h1>{title}</h1><p>{sub}</p></div><button className="primary" onClick={()=>show(keyName)}><Plus size={17}/> Add {title==="QC Tests"?"QC Test":title.replace("Sampling","Sample").replace("Specifications","Specification")}</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered(keyName).length} record(s)</span></div><div className="card"><Table keyName={keyName} columns={cols.map(([k,l])=>({k,l}))}/></div></>}
 };

 return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand side"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="panelTag">Quality / QA-QC</div><nav>{nav.map(([n,I])=><button key={n} className={tab===n?"nav active":"nav"} onClick={()=>go(n)}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideFoot"><span>Logged in as</span><b>{email}</b><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></aside><main><header><button className="menuBtn" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div><b>{tab}</b><span>Quality / QA-QC Panel</span></div><div className="headRight"><span>{BRAND.website}</span><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></header><section className="main">{content()}</section><HowWorks panel="Quality / QA-QC" module={tab}/></main><div className="tour"><div><b>Guide Tour · {tourStep+1}/{tour.length}</b><span>{tour[tourStep][0]} — {tour[tourStep][1]}</span></div><div className="tourBtns"><button disabled={tourStep===0} onClick={()=>setTourStep(Math.max(0,tourStep-1))}>Back</button><button className="primary" onClick={()=>{if(tourStep<tour.length-1){setTourStep(tourStep+1);go(tour[tourStep+1][0])}else notify("Guide tour completed.")}}>{tourStep===tour.length-1?"Finish":"Next"} <ChevronRight size={15}/></button></div></div>{modal&&<Modal keyName={modal}/>} {toast&&<div className="toast">{toast}</div>}</div>;

 function Modal({keyName}){const labels={tests:["sample","parameter","spec","result","unit","date"],samples:["source","ref","product","qty","unit","collectedBy","status"],specs:["product","parameter","target","method","version","status"],capas:["issue","source","owner","due","priority","status"],compliance:["requirement","owner","next","status"]}; const titles={tests:"Add QC Test",samples:"Add Sample",specs:"Add Specification",capas:"Create CAPA",compliance:"Add Compliance Requirement"}; return <div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><div><h2>{titles[keyName]}</h2><p>Enter all required data and save the record.</p></div><button className="iconBtn" onClick={close}><X size={18}/></button></div><div className="formGrid">{labels[keyName].map(k=><label key={k}>{k==="collectedBy"?"Collected By":k.charAt(0).toUpperCase()+k.slice(1)}{k==="status"?<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{(keyName==="tests"?["Pass","Fail","Review"]:keyName==="samples"?["Pending","Collected","Under Test","Approved"]:keyName==="specs"?["Draft","Active","Inactive"]:keyName==="capas"?["Open","In Progress","Closed"]:["Open","Review Due","Compliant"]).map(o=><option key={o}>{o}</option>)}</select>:<input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} type={["date","due","next"].includes(k)?"date":"text"} placeholder={`Enter ${k}`}/>}</label>)}</div><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>add(keyName)}><Save size={17}/> Save Record</button></div></div></div>}
}
