import React,{useState}from"react";
import HowWorks from "../how-works.jsx";
import{LayoutDashboard,ArrowDownToLine,ArrowUpFromLine,Grid3X3,ClipboardList,PackageCheck,BarChart3,Settings,Menu,LogOut,Plus,Search,Trash2,CheckCircle2,Save,X,ChevronRight,Download,AlertTriangle,Edit3}from"lucide-react";
import"./warehouse.css";

const BRAND={name:"TechTarn",website:"www.techtarn.com",phone:"+90 - 7453966757",email:"contact@techtarn.com"};
const PANELS=["Super Admin","Management / CEO","Sales & CRM","Purchase","Production","Quality / QA-QC","Raw Material / Inventory","Warehouse","Food Safety","Maintenance","Machine Operator","Finance & Accounts","HR & Payroll","Logistics / Distribution","Reports & Analytics"];
const DATA={
inward:[
{id:"INW-1001",ref:"GRN-4501",supplier:"Agro Foods Ltd.",item:"Tomato Paste",lot:"TP-260901",qty:"1,200",uom:"kg",bin:"A-01-01",date:"2026-09-28",status:"Received"},
{id:"INW-1002",ref:"GRN-4502",supplier:"Fresh Harvest Co.",item:"Mango Pulp",lot:"MP-260902",qty:"800",uom:"kg",bin:"C-02-03",date:"2026-09-29",status:"Putaway Pending"},
{id:"INW-1003",ref:"GRN-4503",supplier:"ChemSupply Pvt. Ltd.",item:"Citric Acid",lot:"CA-260801",qty:"320",uom:"kg",bin:"D-01-02",date:"2026-09-30",status:"QC Hold"}],
outward:[
{id:"OUT-2001",ref:"DO-7801",customer:"Production Store",item:"Tomato Paste",lot:"TP-260901",qty:"300",uom:"kg",bin:"A-01-01",date:"2026-09-28",status:"Dispatched"},
{id:"OUT-2002",ref:"DO-7802",customer:"Production Store",item:"Mango Pulp",lot:"MP-260902",qty:"200",uom:"kg",bin:"C-02-03",date:"2026-09-29",status:"Picking"},
{id:"OUT-2003",ref:"DO-7803",customer:"Dispatch Warehouse",item:"Sugar",lot:"SG-260903",qty:"500",uom:"kg",bin:"B-03-02",date:"2026-09-30",status:"Ready"}],
bins:[
{id:"BIN-3001",code:"A-01-01",zone:"Raw Material",warehouse:"Main Warehouse",capacity:"2,000",occupied:"1,200",uom:"kg",type:"Pallet",status:"Available"},
{id:"BIN-3002",code:"B-03-02",zone:"Dry Store",warehouse:"Main Warehouse",capacity:"3,000",occupied:"1,500",uom:"kg",type:"Pallet",status:"Available"},
{id:"BIN-3003",code:"C-02-03",zone:"Cold Store",warehouse:"Cold Warehouse",capacity:"1,500",occupied:"1,000",uom:"kg",type:"Cold",status:"Available"},
{id:"BIN-3004",code:"D-01-02",zone:"Quarantine",warehouse:"Main Warehouse",capacity:"800",occupied:"320",uom:"kg",type:"QC Hold",status:"Reserved"}],
picking:[
{id:"PCK-4001",order:"DO-7801",item:"Tomato Paste",lot:"TP-260901",qty:"300",uom:"kg",picker:"Ravi Kumar",bin:"A-01-01",started:"2026-09-28 08:20",status:"Completed"},
{id:"PCK-4002",order:"DO-7802",item:"Mango Pulp",lot:"MP-260902",qty:"200",uom:"kg",picker:"Neha Singh",bin:"C-02-03",started:"2026-09-29 09:10",status:"In Progress"},
{id:"PCK-4003",order:"DO-7803",item:"Sugar",lot:"SG-260903",qty:"500",uom:"kg",picker:"Amit Verma",bin:"B-03-02",started:"2026-09-30 10:00",status:"Pending"}],
packing:[
{id:"PKG-5001",order:"DO-7801",item:"Tomato Paste",qty:"300",uom:"kg",packages:"30",packer:"Pooja Sharma",type:"Carton",date:"2026-09-28",status:"Packed"},
{id:"PKG-5002",order:"DO-7802",item:"Mango Pulp",qty:"200",uom:"kg",packages:"20",packer:"Karan Singh",type:"Crate",date:"2026-09-29",status:"In Progress"},
{id:"PKG-5003",order:"DO-7803",item:"Sugar",qty:"500",uom:"kg",packages:"50",packer:"Asha Gupta",type:"Bag",date:"2026-09-30",status:"Pending"}]
};
const EMPTY={
inward:{ref:"",supplier:"",item:"",lot:"",qty:"",uom:"kg",bin:"",date:"",status:"Received"},
outward:{ref:"",customer:"",item:"",lot:"",qty:"",uom:"kg",bin:"",date:"",status:"Ready"},
bins:{code:"",zone:"",warehouse:"",capacity:"",occupied:"0",uom:"kg",type:"Pallet",status:"Available"},
picking:{order:"",item:"",lot:"",qty:"",uom:"kg",picker:"",bin:"",started:"",status:"Pending"},
packing:{order:"",item:"",qty:"",uom:"kg",packages:"",packer:"",type:"Carton",date:"",status:"Pending"}
};
const TOUR=[["Dashboard","Review warehouse workload, bin utilization and pending operations."],["Inward","Receive materials, assign bins and complete putaway."],["Outward","Process material issues and dispatch quantities."],["Bin Management","Maintain zones, capacities, occupancy and bin status."],["Picking","Assign pickers and track order picking progress."],["Packing","Record package details and complete packing."],["Reports","Export warehouse performance summaries."],["Settings","Save warehouse operating preferences."]];

export default function App(){
const[logged,setLogged]=useState(true),[email,setEmail]=useState("warehouse@techtarn.com"),[password,setPassword]=useState("Demo@123"),[panel,setPanel]=useState("Warehouse"),[tab,setTab]=useState("Dashboard"),[mobile,setMobile]=useState(false),[query,setQuery]=useState(""),[data,setData]=useState(DATA),[modal,setModal]=useState(null),[form,setForm]=useState(null),[toast,setToast]=useState(""),[tour,setTour]=useState(0);
const nav=[["Dashboard",LayoutDashboard],["Inward",ArrowDownToLine],["Outward",ArrowUpFromLine],["Bin Management",Grid3X3],["Picking",ClipboardList],["Packing",PackageCheck],["Reports",BarChart3],["Settings",Settings]];
const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)},go=n=>{setTab(n);setMobile(false)},show=k=>{setModal(k);setForm({...EMPTY[k]})},close=()=>{setModal(null);setForm(null)};
const keyFor=t=>({Inward:"inward",Outward:"outward","Bin Management":"bins",Picking:"picking",Packing:"packing"}[t]);
const filtered=k=>data[k].filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
const add=k=>{const p={inward:"INW",outward:"OUT",bins:"BIN",picking:"PCK",packing:"PKG"}[k];const id=`${p}-${String(data[k].length+1).padStart(4,"0")}`;setData({...data,[k]:[{id,...form},...data[k]]});close();notify("Record saved successfully.")};
const del=(k,id)=>{setData({...data,[k]:data[k].filter(r=>r.id!==id)});notify("Record deleted.")};
const status=(k,id,s)=>{setData({...data,[k]:data[k].map(r=>r.id===id?{...r,status:s}:r)});notify(`Status updated to ${s}.`)};
const login=e=>{e.preventDefault();if((email==="warehouse@techtarn.com"||email==="admin@techtarn.com")&&password==="Demo@123")setLogged(true);else notify("Use the demo credentials.")};
if(!logged)return <div className="login"><div className="loginCard"><div className="brand"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="loginTitle"><h1>Warehouse</h1><p>Inward • Outward • Bin Management • Picking • Packing</p></div><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Panel<select value={panel} onChange={e=>setPanel(e.target.value)}>{PANELS.map(x=><option key={x}>{x}</option>)}</select></label><button className="primary wide">Login <ChevronRight size={17}/></button></form><div className="demo">Demo: warehouse@techtarn.com / Demo@123</div></div></div>;

const counts={inward:data.inward.length,outward:data.outward.length,bins:data.bins.length,picking:data.picking.filter(x=>x.status!=="Completed").length,packing:data.packing.filter(x=>x.status!=="Packed").length};
const Table=({k,cols})=><div className="tableWrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}<th>Actions</th></tr></thead><tbody>{filtered(k).map(r=><tr key={r.id}>{cols.map(c=><td key={c[0]}>{c[0]==="status"?<span className={`badge ${String(r[c[0]]).toLowerCase().replaceAll(" ","-")}`}>{r[c[0]]}</span>:r[c[0]]}</td>)}<td className="actions">{k==="inward"&&r.status==="Putaway Pending"&&<button className="iconBtn" title="Complete putaway" onClick={()=>status(k,r.id,"Received")}><CheckCircle2 size={15}/></button>}{k==="outward"&&r.status!=="Dispatched"&&<button className="iconBtn" title="Dispatch" onClick={()=>status(k,r.id,"Dispatched")}><CheckCircle2 size={15}/></button>}{k==="picking"&&r.status!=="Completed"&&<button className="iconBtn" title="Complete picking" onClick={()=>status(k,r.id,"Completed")}><CheckCircle2 size={15}/></button>}{k==="packing"&&r.status!=="Packed"&&<button className="iconBtn" title="Complete packing" onClick={()=>status(k,r.id,"Packed")}><CheckCircle2 size={15}/></button>}{k==="bins"&&r.status==="Reserved"&&<button className="iconBtn" title="Release bin" onClick={()=>status(k,r.id,"Available")}><CheckCircle2 size={15}/></button>}<button className="iconBtn danger" title="Delete" onClick={()=>del(k,r.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>;

const moduleView=(title,sub,k,cols,label)=><><div className="hero compact"><div><p className="eyebrow">WAREHOUSE</p><h1>{title}</h1><p>{sub}</p></div><button className="primary" onClick={()=>show(k)}><Plus size={17}/>{label}</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered(k).length} record(s)</span></div><div className="card"><Table k={k} cols={cols}/></div></>;

const content=()=>{
if(tab==="Dashboard")return <><div className="hero"><div><p className="eyebrow">WAREHOUSE CONTROL CENTER</p><h1>Warehouse Dashboard</h1><p>Control receiving, dispatch, bins, picking and packing from one workspace.</p></div><button className="primary" onClick={()=>show("inward")}><Plus size={17}/> New Inward</button></div><div className="stats">{[["Inward",counts.inward,ArrowDownToLine,"Inward"],["Outward",counts.outward,ArrowUpFromLine,"Outward"],["Bins",counts.bins,Grid3X3,"Bin Management"],["Open Picking",counts.picking,ClipboardList,"Picking"],["Open Packing",counts.packing,PackageCheck,"Packing"]].map(([l,v,I,t])=><div className="stat" key={l}><div className="statIcon"><I size={18}/></div><div><span>{l}</span><strong>{v}</strong></div><button onClick={()=>go(t)}>Open</button></div>)}</div><div className="grid2"><div className="card"><div className="cardHead"><div><h3>Warehouse workflow</h3><p>Follow material movement from receipt to dispatch.</p></div></div>{["Inward receipt","Bin putaway","Outward issue","Picking","Packing"].map((x,i)=><div className="workflow" key={x}><b>{i+1}</b><span>{x}</span><ChevronRight size={16}/></div>)}</div><div className="card"><div className="cardHead"><div><h3>Attention required</h3><p>Current warehouse workload.</p></div></div><div className="alert"><AlertTriangle size={17}/><span><b>{data.inward.filter(x=>x.status==="Putaway Pending").length}</b> inward item(s) awaiting putaway</span></div><div className="alert"><AlertTriangle size={17}/><span><b>{data.outward.filter(x=>x.status!=="Dispatched").length}</b> outward order(s) not dispatched</span></div><div className="alert"><ClipboardList size={17}/><span><b>{counts.picking}</b> picking task(s) open</span></div><div className="alert"><PackageCheck size={17}/><span><b>{counts.packing}</b> packing task(s) open</span></div></div></div></>;
if(tab==="Inward")return moduleView("Inward","Receive materials, assign bins and track receipt status.","inward",[["id","Inward ID"],["ref","Reference"],["supplier","Supplier"],["item","Item"],["lot","Lot"],["qty","Qty"],["uom","UOM"],["bin","Bin"],["date","Date"],["status","Status"]],"Add Inward");
if(tab==="Outward")return moduleView("Outward","Process material issues, picking references and dispatch status.","outward",[["id","Outward ID"],["ref","Reference"],["customer","Destination"],["item","Item"],["lot","Lot"],["qty","Qty"],["uom","UOM"],["bin","Bin"],["date","Date"],["status","Status"]],"Add Outward");
if(tab==="Bin Management")return moduleView("Bin Management","Maintain warehouse zones, capacities, occupancy and availability.","bins",[["id","Bin ID"],["code","Bin Code"],["zone","Zone"],["warehouse","Warehouse"],["capacity","Capacity"],["occupied","Occupied"],["uom","UOM"],["type","Type"],["status","Status"]],"Add Bin");
if(tab==="Picking")return moduleView("Picking","Assign pickers and track order-level picking progress.","picking",[["id","Pick ID"],["order","Order"],["item","Item"],["lot","Lot"],["qty","Qty"],["uom","UOM"],["picker","Picker"],["bin","Bin"],["started","Started"],["status","Status"]],"Create Pick");
if(tab==="Packing")return moduleView("Packing","Record package quantities, packers and packing status.","packing",[["id","Pack ID"],["order","Order"],["item","Item"],["qty","Qty"],["uom","UOM"],["packages","Packages"],["packer","Packer"],["type","Type"],["date","Date"],["status","Status"]],"Create Packing");
if(tab==="Reports")return <><div className="hero compact"><div><p className="eyebrow">REPORTING</p><h1>Warehouse Reports</h1><p>Review receiving, dispatch, bin, picking and packing activity.</p></div><button className="secondary" onClick={()=>notify("Warehouse report export prepared.")}><Download size={17}/> Export Report</button></div><div className="reportGrid">{[["Inward",counts.inward,"Receipts recorded"],["Outward",counts.outward,"Issues recorded"],["Bins",counts.bins,"Warehouse locations"],["Open Picking",counts.picking,"Tasks requiring completion"],["Open Packing",counts.packing,"Packing tasks open"]].map(([a,b,c])=><div className="reportCard" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small><div className="bar"><i style={{width:`${Math.min(100,Math.max(12,b*18))}%`}}/></div></div>)}</div></>;
return <div className="card settings"><div className="cardHead"><div><h2>Warehouse Settings</h2><p>Configure warehouse operating preferences for this prototype.</p></div></div><div className="formGrid"><label>Default Warehouse<input defaultValue="Main Warehouse"/></label><label>Putaway Rule<select defaultValue="Bin Capacity"><option>Bin Capacity</option><option>Fixed Bin</option><option>Zone Priority</option></select></label><label>Picking Method<select defaultValue="FIFO"><option>FIFO</option><option>FEFO</option><option>Manual</option></select></label><label>Packing Station<input defaultValue="Packing Station 01"/></label></div><button className="primary" onClick={()=>notify("Settings saved successfully.")}><Save size={17}/> Save Settings</button></div>;
};

const fields={inward:["ref","supplier","item","lot","qty","uom","bin","date","status"],outward:["ref","customer","item","lot","qty","uom","bin","date","status"],bins:["code","zone","warehouse","capacity","occupied","uom","type","status"],picking:["order","item","lot","qty","uom","picker","bin","started","status"],packing:["order","item","qty","uom","packages","packer","type","date","status"]};
const titles={inward:"Add Inward",outward:"Add Outward",bins:"Add Bin",picking:"Create Pick",packing:"Create Packing"};
const opts={inward:["Received","Putaway Pending","QC Hold"],outward:["Ready","Picking","Dispatched"],bins:["Available","Reserved","Blocked"],picking:["Pending","In Progress","Completed"],packing:["Pending","In Progress","Packed"]};
const Modal=({k})=><div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><div><h2>{titles[k]}</h2><p>Enter the warehouse data and save the record.</p></div><button className="iconBtn" onClick={close}><X size={18}/></button></div><div className="formGrid">{fields[k].map(f=><label key={f}>{f==="uom"?"UOM":f.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())}{f==="status"?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{opts[k].map(o=><option key={o}>{o}</option>)}</select>:<input required value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})} type={["date"].includes(f)?"date":"text"} placeholder={`Enter ${f}`}/>}</label>)}</div><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>add(k)}><Save size={17}/> Save Record</button></div></div></div>;

return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand side"><div className="logo">T</div><div><b>{BRAND.name}</b><span>Food Processing ERP</span></div></div><div className="panelTag">Warehouse</div><nav>{nav.map(([n,I])=><button key={n} className={tab===n?"nav active":"nav"} onClick={()=>go(n)}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideFoot"><span>Logged in as</span><b>{email}</b><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></aside><main><header><button className="menuBtn" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div><b>{tab}</b><span>Warehouse Panel</span></div><div className="headRight"><span>{BRAND.website}</span><button onClick={()=>setLogged(false)}><LogOut size={16}/> Logout</button></div></header><section className="main">{content()}</section><HowWorks panel="Warehouse" module={tab}/></main><div className="tour"><div><b>Guide Tour · {tour+1}/{TOUR.length}</b><span>{TOUR[tour][0]} — {TOUR[tour][1]}</span></div><div className="tourBtns"><button disabled={tour===0} onClick={()=>setTour(Math.max(0,tour-1))}>Back</button><button className="primary" onClick={()=>{if(tour<TOUR.length-1){setTour(tour+1);go(TOUR[tour+1][0])}else notify("Guide tour completed.")}}>{tour===TOUR.length-1?"Finish":"Next"} <ChevronRight size={15}/></button></div></div>{modal&&<Modal k={modal}/>} {toast&&<div className="toast">{toast}</div>}</div>;
}
